'use client';
import { useEffect, useState } from 'react';
import { deliveryBlockers, quantityCalculationTotal, type DeliveryReview, type QuantityCalculation, type RequirementReference } from '@/lib/project-delivery';

type Loaded = {review:DeliveryReview;revision:number;productRevision:number;canEdit:boolean;stale:boolean;references:RequirementReference[]};
const input='w-full rounded border border-slate-300 bg-white px-2 py-1.5 text-sm text-slate-900';
const button='rounded border border-slate-300 bg-white px-3 py-2 text-sm font-semibold disabled:opacity-50';
export function PostDeliveryReview({projectId,requirementId,selectedNumbers,productDirty,onDirtyChange,onSavingChange,onApplyQuantity,onChooseAlternative}: {
  projectId:string;requirementId:string;selectedNumbers:string[];productDirty:boolean;onDirtyChange:(dirty:boolean)=>void;onSavingChange:(saving:boolean)=>void;
  onApplyQuantity:(target:string,quantity:number,unit:string)=>void;onChooseAlternative:(number:string,name:string)=>void;
}) {
  const [data,setData]=useState<Loaded|null>(null),[review,setReview]=useState<DeliveryReview|null>(null);
  const [dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{const controller=new AbortController(); fetch(`/api/projects/${projectId}/delivery?requirementId=${requirementId}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const p=await r.json();if(!r.ok)throw Error(p.error);setData(p);setReview(p.review);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return ()=>controller.abort();},[projectId,requirementId]);
  useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
  useEffect(()=>{onSavingChange(busy);return()=>onSavingChange(false);},[busy,onSavingChange]);
  function change(next:DeliveryReview){setReview({...next,state:'draft'});setDirty(true);setNotice('');}
  async function save(state:'draft'|'ready'){
    if(!data||!review)return;setBusy(true);setError('');
    try{const r=await fetch(`/api/projects/${projectId}/delivery`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'review',requirementId,revision:data.revision,productRevision:data.productRevision,review:{...review,state}})});const p=await r.json();if(!r.ok)throw Error(p.error);setData({...data,revision:p.revision,stale:false});setReview({...review,state});setDirty(false);setNotice(state==='ready'?'Leveransen är kontrollerad.':'Utkast sparat.');}catch(e){setError(e instanceof Error?e.message:'Kunde inte spara.');}finally{setBusy(false);}
  }
  const blockers=review?deliveryBlockers(review,selectedNumbers):[];
  return <section className="mx-4 my-4 rounded-lg border border-slate-300 bg-slate-50 text-slate-900">
    <header className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 px-4 py-3"><h3 className="font-bold">Leveranskontroll</h3><span className="text-sm">{data?.stale?'Produktvalet har ändrats – granska igen':review?.state==='ready'?'Kontrollerad leverans':'Återstår att granska'}</span></header>
    {error&&<p role="alert" className="p-4 text-red-800">{error}</p>}
    {!review&&!error&&<p className="p-4">Laddar leveranskontroll…</p>}
    {data&&review&&<div className="space-y-4 p-4">
      {!data.canEdit&&<p className="rounded bg-amber-100 p-3">Du kan läsa hela projektet. Den här posten kan bara ändras av ansvarig person eller projektansvarig.</p>}
      <details open={data.references.some(r=>r.conflicts.length>0)}><summary className="cursor-pointer font-semibold">Krav från huvudposter och hänvisningar ({data.references.length})</summary>
        <ul className="mt-2 space-y-2 text-sm">{data.references.map(ref=><li key={`${ref.kind}:${ref.post}`} className="rounded border bg-white p-3"><strong>{ref.kind==='parent'?'Huvudpost':'Hänvisning'} {ref.post}</strong> — {ref.state==='missing'?'Källpost saknas i inlästa underlag':ref.state==='ambiguous'?'Flera källposter finns – välj rätt underlag vid granskning':ref.description}
          {ref.documentId&&<a className="ml-2 underline" target="_blank" rel="noreferrer" href={`/api/projects/${projectId}/documents/${ref.documentId}/file#page=${ref.page??1}`}>Källa, sida {ref.page??'?'}</a>}
          {ref.conflicts.length>0&&<p className="mt-1 text-amber-900">Olika uppgifter – kontrollera vilket krav som gäller: {ref.conflicts.join('; ')}</p>}</li>)}</ul>
      </details>
      <fieldset disabled={!data.canEdit||busy} className="space-y-4 disabled:opacity-75">
        <details open><summary className="cursor-pointer font-semibold">Delar som ska ingå</summary>
          <p className="my-2 text-sm text-slate-600">Markera vad som ingår i huvudprodukten, vad som väljs separat och vad som undantas. Hänvisa till underlag för beslutet.</p>
          {review.components.map((part,i)=><div key={part.id} className="mb-2 grid gap-2 rounded border bg-white p-3 md:grid-cols-2"><label className="text-sm font-semibold">{part.label}{part.optional?' (valfri)':''}<select aria-label={`Status ${part.label}`} className={input} value={part.status} onChange={e=>change({...review,components:review.components.map((p,j)=>i===j?{...p,status:e.target.value as typeof p.status}:p)})}><option value="missing">Saknas / ej kontrollerad</option><option value="included">Ingår i huvudprodukten</option><option value="separate">Separat tillbehör</option><option value="excluded">Undantas med motivering</option></select></label>
            <label className="text-sm">{part.status==='separate'?'Artikel bland valda tillbehör':'Underlag / motivering'}{part.status==='separate'?<select className={input} value={part.productNumber} onChange={e=>change({...review,components:review.components.map((p,j)=>i===j?{...p,productNumber:e.target.value}:p)})}><option value="">Välj sparat tillbehör</option>{selectedNumbers.slice(1).map(n=><option key={n}>{n}</option>)}</select>:<input className={input} value={part.note} maxLength={2000} onChange={e=>change({...review,components:review.components.map((p,j)=>i===j?{...p,note:e.target.value}:p)})}/>}</label></div>)}
          <button type="button" className={button} onClick={()=>change({...review,components:[...review.components,{id:crypto.randomUUID(),label:'Ny leveransdel',status:'missing',productNumber:'',note:'',optional:false}]})}>Lägg till leveransdel</button>
          {review.components.filter(p=>p.id.includes('-')&&p.label==='Ny leveransdel').map(part=><label key={part.id} className="mt-2 block text-sm">Namn på ny del<input className={input} defaultValue={part.label} maxLength={240} onBlur={e=>change({...review,components:review.components.map(p=>p.id===part.id?{...p,label:e.target.value.trim()||'Ny leveransdel'}:p)})}/></label>)}
        </details>
        <details><summary className="cursor-pointer font-semibold">Avvikelser och beslut ({review.deviations.length})</summary>
          {review.deviations.map((d,i)=><div key={d.id} className="my-2 space-y-2 rounded border bg-white p-3"><label className="block text-sm">Krav och avvikelse<textarea className={input} maxLength={2000} value={d.description} onChange={e=>change({...review,deviations:review.deviations.map((v,j)=>j===i?{...v,description:e.target.value}:v)})}/></label><div className="grid gap-2 md:grid-cols-2"><label className="text-sm">Beslutsansvarig<input className={input} value={d.owner} maxLength={200} onChange={e=>change({...review,deviations:review.deviations.map((v,j)=>j===i?{...v,owner:e.target.value}:v)})}/></label><label className="text-sm">Beslut<select className={input} value={d.decision} onChange={e=>change({...review,deviations:review.deviations.map((v,j)=>j===i?{...v,decision:e.target.value as typeof v.decision}:v)})}><option value="open">Inväntar beslut</option><option value="accepted">Avvikelsen accepteras</option><option value="rejected">Avvikelsen avslås / åtgärdad</option></select></label></div><label className="block text-sm">Motivering / beslutsunderlag<input className={input} value={d.reason} maxLength={2000} onChange={e=>change({...review,deviations:review.deviations.map((v,j)=>j===i?{...v,reason:e.target.value}:v)})}/></label></div>)}
          <button type="button" className={button} onClick={()=>change({...review,deviations:[...review.deviations,{id:crypto.randomUUID(),description:'',owner:'',decision:'open',reason:''}]})}>Registrera avvikelse</button>
        </details>
        <details><summary className="cursor-pointer font-semibold">Alternativ utanför materiallistan ({review.alternatives.length})</summary><p className="my-2 text-sm">Ett alternativ räknas först när det väljs och sparas som postens huvudprodukt.</p>
          {review.alternatives.map((a,i)=><div className="my-2 grid gap-2 rounded border bg-white p-3 md:grid-cols-2" key={a.id}>{(['name','productNumber','reason'] as const).map(key=><label key={key} className="text-sm">{{name:'Produktnamn',productNumber:'Artikelnummer',reason:'Skillnad mot kravet'}[key]}<input className={input} value={a[key]} maxLength={key==='reason'?2000:key==='name'?240:120} onChange={e=>change({...review,alternatives:review.alternatives.map((v,j)=>i===j?{...v,[key]:e.target.value}:v)})}/></label>)}<button type="button" className={button} disabled={!a.productNumber||!a.name||dirty} onClick={()=>onChooseAlternative(a.productNumber,a.name)}>Välj för kontroll</button></div>)}
          <button type="button" className={button} onClick={()=>change({...review,alternatives:[...review.alternatives,{id:crypto.randomUUID(),name:'',productNumber:'',reason:''}]})}>Lägg till alternativ</button>
        </details>
        <details><summary className="cursor-pointer font-semibold">Mängdberäkningar ({review.calculations.length})</summary><p className="my-2 text-sm">Varje beräkning gäller denna post. Granska faktorn och använd sedan mängden i produktvalet.</p>
          {review.calculations.map((calc,i)=>{const update=(patch:Partial<QuantityCalculation>)=>change({...review,calculations:review.calculations.map((c,j)=>i===j?{...c,...patch,reviewed:'reviewed' in patch?Boolean(patch.reviewed):false}:c)});return <div key={calc.id} className="my-2 space-y-2 rounded border bg-white p-3"><label className="block text-sm">Produkt / tillbehör<select className={input} value={calc.target} onChange={e=>update({target:e.target.value})}><option value="">Välj artikel</option>{selectedNumbers.map(n=><option key={n}>{n}</option>)}</select></label><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{(['base','baseUnit','factor','unit'] as const).map(key=><label className="text-sm" key={key}>{{base:'Grundmängd',baseUnit:'Grundenhet',factor:'Faktor per enhet',unit:'Beställningsenhet'}[key]}<input className={input} type={key==='base'||key==='factor'?'number':'text'} step="any" min="0.001" value={calc[key]} onChange={e=>update({[key]:key==='base'||key==='factor'?Number(e.target.value):e.target.value})}/></label>)}</div><label className="block text-sm">Källa och beräkningsgrund<input className={input} value={calc.source} maxLength={1000} onChange={e=>update({source:e.target.value})}/></label><div className="flex flex-wrap items-center gap-3"><strong>{calc.base} {calc.baseUnit} × {calc.factor} = {quantityCalculationTotal(calc)??'Ogiltig mängd'} {calc.unit}</strong><label className="text-sm"><input type="checkbox" checked={calc.reviewed} onChange={e=>update({reviewed:e.target.checked})}/> Faktorn är kontrollerad</label><button type="button" className={button} disabled={!calc.reviewed||!calc.source||!selectedNumbers.includes(calc.target)||quantityCalculationTotal(calc)===null} onClick={()=>{onApplyQuantity(calc.target,quantityCalculationTotal(calc)!,calc.unit);setNotice('Mängden är införd i produktvalet. Spara leveransutkastet och sedan produktvalet.');}}>Använd mängd</button></div></div>;})}
          <button type="button" className={button} onClick={()=>change({...review,calculations:[...review.calculations,{id:crypto.randomUUID(),target:'',base:1,baseUnit:'st',factor:1,unit:'st',source:'',reviewed:false}]})}>Ny mängdberäkning</button>
        </details>
        {blockers.length>0&&<details><summary className="cursor-pointer text-sm font-semibold text-amber-900">{blockers.length} punkter återstår</summary><ul className="list-disc pl-5 text-sm">{blockers.map((b,i)=><li key={i}>{b}</li>)}</ul></details>}
        <div className="flex flex-wrap items-center gap-3"><button className={button} type="button" disabled={!dirty||busy} onClick={()=>void save('draft')}>Spara leveransutkast</button><button className={`${button} bg-slate-900 text-white`} type="button" disabled={busy||productDirty||!selectedNumbers[0]||blockers.length>0} onClick={()=>void save('ready')}>Markera leverans kontrollerad</button>{productDirty&&<span className="text-sm">Spara produktvalet innan leveransen godkänns.</span>}</div>
      </fieldset>
      {notice&&<p role="status" className="text-sm text-emerald-800">{notice}</p>}
    </div>}
  </section>;
}
