'use client';
import { useEffect, useState, type FormEvent } from 'react';
import type { DeliveryReview, RevisionDifference } from '@/lib/project-delivery';
type Package={id:string;scope_type:'chapter'|'group';scope_value:string;assigned_to:string;due_date:string|null;note:string;revision:number};
type Doc={id:string;file_name:string;state:string;role:string;revision_label:string;revision:number;fileId?:string};
type Data={manager:boolean;enforced:boolean;userId:string;packages:Package[];members:{user_id:string;label:string}[];documents:Doc[];reviews:{requirement_id:string;product_revision:number;review:DeliveryReview}[];requirements:{id:string;category:string;edit_revision:number;value_json:unknown;actionable?:boolean}[]};
const input='w-full rounded border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900';
const button='rounded border border-slate-300 bg-white px-3 py-2 text-sm font-semibold disabled:opacity-50';
export function ProjectDeliveryControl({projectId,mode,onChanged}:{projectId:string;mode:'assignments'|'documents';onChanged:()=>Promise<unknown>}) {
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
  const [editing,setEditing]=useState<Package|null>(null),[documentId,setDocumentId]=useState(''),[replaces,setReplaces]=useState(''),[role,setRole]=useState('specification'),[label,setLabel]=useState('');
  const [comparison,setComparison]=useState<RevisionDifference[]|null>(null),[notice,setNotice]=useState('');
  const [history,setHistory]=useState<{id:string;postNumber:string;status:string;product_snapshot:{name?:string;productNumber?:string}}[]|null>(null);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/projects/${projectId}/delivery`,{cache:'no-store',signal:controller.signal}).then(async r=>{const p=await r.json();if(!r.ok)throw Error(p.error);setData(p);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[projectId,revision]);
  async function mutate(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const r=await fetch(`/api/projects/${projectId}/delivery`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw Error(p.error);setRevision(v=>v+1);await onChanged();setNotice('Ändringen är sparad.');return true;}catch(e){setError(e instanceof Error?e.message:'Kunde inte spara.');return false;}finally{setBusy(false);}}
  async function saveAssignment(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const ok=await mutate({action:'assignment',revision:editing?.revision,payload:{id:editing?.id,scope_type:editing?.scope_type??form.get('scope_type'),scope_value:editing?.scope_value??form.get('scope_value'),assigned_to:form.get('assigned_to'),due_date:form.get('due_date'),note:form.get('note')}});if(ok)setEditing(null);}
  async function compare(){setBusy(true);setError('');try{const r=await fetch(`/api/projects/${projectId}/delivery?before=${replaces}&after=${documentId}`,{cache:'no-store'});const p=await r.json();if(!r.ok)throw Error(p.error);setComparison(p.differences);}catch(e){setError(e instanceof Error?e.message:'Jämförelsen misslyckades.');}finally{setBusy(false);}}
  async function showHistory(id:string){setBusy(true);setError('');try{const r=await fetch(`/api/projects/${projectId}/delivery?history=${id}`,{cache:'no-store'});const p=await r.json();if(!r.ok)throw Error(p.error);setHistory(p.history);}catch(e){setError(e instanceof Error?e.message:'Historiken kunde inte läsas.');}finally{setBusy(false);}}
  const selected=data?.documents.find(d=>d.id===documentId);
  const owner=(id:string)=>data?.members.find(m=>m.user_id===id)?.label??id;
  function assignedPackage(req:Data['requirements'][number]){const post=typeof req.value_json==='string'?req.value_json:'';return data?.packages.filter(p=>p.scope_type==='chapter'?(post===p.scope_value||post.startsWith(`${p.scope_value}.`)):p.scope_value===req.category).sort((a,b)=>Number(b.scope_type==='chapter')-Number(a.scope_type==='chapter')||b.scope_value.length-a.scope_value.length)[0];}
  const unassigned=data?.requirements.filter(r=>!assignedPackage(r)).length??0;
  return <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-5 text-slate-900 shadow-sm">
    <h2 className="text-lg font-bold">{mode==='assignments'?'Ansvar och leveransstatus':'Dokumentroller och revisioner'}</h2>
    {error&&<p role="alert" className="text-red-800">{error} <button type="button" className="underline" onClick={()=>{setError('');setRevision(v=>v+1);}}>Försök igen</button></p>}
    {!data&&!error&&<p>Laddar projektstyrning…</p>}
    {data&&mode==='assignments'&&<>
      <p className="text-sm text-slate-600">Alla projektmedlemmar kan läsa hela projektet. När tilldelning används kan varje person ändra sin tilldelade del. Projektansvarig kan hantera alla delar. En mer specifik posttilldelning gäller före en produktgrupp.</p>
      <div className="grid gap-3 sm:grid-cols-3">{[[data.requirements.length,'Aktiva poster'],[unassigned,'Utan tilldelning'],[data.reviews.filter(w=>w.review.state==='ready'&&data.requirements.some(r=>r.id===w.requirement_id&&r.edit_revision===w.product_revision)).length,'Kontrollerade leveranser']].map(([count,title])=><div className="rounded-lg bg-slate-100 p-4" key={title}><strong className="block text-2xl">{count}</strong><span className="text-sm">{title}</span></div>)}</div>
      {data.enforced&&unassigned>0&&<p className="rounded bg-amber-50 p-3 text-sm text-amber-900">Poster utan tilldelning kan ändras av projektansvarig. Fördela dem för att teamet ska kunna arbeta vidare.</p>}
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Område</th><th>Ansvarig</th><th>Deadline</th><th>Leveranser</th><th>Öppna avvikelser</th><th /></tr></thead><tbody>{data.packages.map(p=>{const reqs=data.requirements.filter(r=>r.actionable!==false && assignedPackage(r)?.id===p.id);const reviews=data.reviews.filter(w=>reqs.some(r=>r.id===w.requirement_id));const complete=reviews.filter(w=>w.review.state==='ready'&&reqs.some(r=>r.id===w.requirement_id&&r.edit_revision===w.product_revision)).length;const overdue=Boolean(p.due_date&&p.due_date<new Date().toLocaleDateString('sv-SE')&&complete<reqs.length);return <tr key={p.id} className="border-b"><td className="p-2 font-semibold">{p.scope_type==='chapter'?'Post':'Grupp'} {p.scope_value}</td><td>{owner(p.assigned_to)}</td><td className={overdue?'font-semibold text-red-700':''}>{p.due_date??'Ej satt'}{overdue?' · Försenat':''}</td><td>{complete} / {reqs.length}</td><td>{reviews.reduce((n,w)=>n+w.review.deviations.filter(d=>d.decision==='open').length,0)}</td><td>{data.manager&&<button type="button" className={button} onClick={()=>setEditing(p)}>Ändra ansvar</button>}</td></tr>;})}</tbody></table></div>
      {data.manager&&<form key={editing?.id??'new'} onSubmit={saveAssignment} className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">{editing?`Ändra ${editing.scope_value}`:'Tilldela ett område'}</h3><fieldset disabled={busy} className="grid gap-3 md:grid-cols-3"><label className="text-sm">Områdestyp<select name="scope_type" className={input} defaultValue={editing?.scope_type??'chapter'} disabled={Boolean(editing)}><option value="chapter">Postnummer med underposter</option><option value="group">Produktgrupp</option></select></label><label className="text-sm">Postnummer eller produktgrupp<input name="scope_value" list={`delivery-groups-${projectId}`} className={input} defaultValue={editing?.scope_value} disabled={Boolean(editing)} placeholder="30.332.7" required maxLength={160}/><datalist id={`delivery-groups-${projectId}`}>{[...new Set(data.requirements.map(r=>r.category))].map(c=><option key={c}>{c}</option>)}</datalist></label><label className="text-sm">Ansvarig<select name="assigned_to" className={input} defaultValue={editing?.assigned_to??''} required><option value="">Välj person</option>{data.members.map(m=><option key={m.user_id} value={m.user_id}>{m.label}</option>)}</select></label><label className="text-sm">Deadline<input className={input} type="date" name="due_date" defaultValue={editing?.due_date??''}/></label><label className="text-sm md:col-span-2">Instruktion till ansvarig<input className={input} name="note" maxLength={2000} defaultValue={editing?.note??''}/></label><button type="submit" className={button}>{busy?'Sparar…':'Spara tilldelning'}</button>{editing&&<button type="button" className={button} onClick={()=>setEditing(null)}>Avbryt</button>}</fieldset></form>}
    </>}
    {data&&mode==='documents'&&<>
      <p className="text-sm text-slate-600">Specifikationer skapar aktiva produktposter. Offerter, mängdunderlag och referenser sparas som underlag. Nya dokument väntar på aktivering så att samma poster inte räknas dubbelt.</p>
      <ul className="divide-y">{data.documents.map(d=><li key={d.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><strong className="text-sm">{d.file_name}</strong><p className="text-xs text-slate-600">{{specification:'Specifikation',offer:'Offert',quantity:'Mängdunderlag',reference:'Referens'}[d.role]??d.role} · {d.revision_label||'Revision ej angiven'} · {{pending:'Väntar på granskning',active:'Aktivt',superseded:'Ersatt – historik'}[d.state]??d.state}</p></div>{d.fileId&&<a className="text-sm underline" target="_blank" rel="noreferrer" href={`/api/projects/${projectId}/documents/${d.fileId}/file`}>Öppna PDF</a>}{d.state==="superseded"&&<button type="button" className={button} disabled={busy} onClick={()=>void showHistory(d.id)}>Tidigare produktval</button>}{data.manager&&d.state!=='superseded'&&<button type="button" className={button} onClick={()=>{setDocumentId(d.id);setRole(d.role);setLabel(d.revision_label);setReplaces('');setComparison(null);}}>Hantera dokument</button>}</li>)}</ul>
      {history&&<section className="rounded border p-3"><h3 className="font-semibold">Tidigare produktval</h3>{history.length===0?<p className="text-sm">Inga tidigare val finns i dokumentet.</p>:<ul className="max-h-64 overflow-auto text-sm">{history.map(h=><li key={h.id} className="border-b py-2">Post {h.postNumber}: {h.product_snapshot.name} · {h.product_snapshot.productNumber} · {h.status==="selected"?"Vald":"Historiskt val – räknas inte i materiallistan"}</li>)}</ul>}</section>}{selected&&data.manager&&<div className="space-y-3 rounded border bg-slate-50 p-4"><h3 className="font-semibold">{selected.file_name}</h3><fieldset disabled={busy} className="space-y-3"><div className="grid gap-3 md:grid-cols-3"><label className="text-sm">Dokumentroll<select className={input} value={role} onChange={e=>setRole(e.target.value)}><option value="specification">Specifikation</option><option value="offer">Offert</option><option value="quantity">Mängdunderlag</option><option value="reference">Referens</option></select></label><label className="text-sm">Revisionsbeteckning<input className={input} value={label} maxLength={120} onChange={e=>setLabel(e.target.value)}/></label><label className="text-sm">Ersätter tidigare dokument<select className={input} value={replaces} onChange={e=>{setReplaces(e.target.value);setComparison(null);}}><option value="">Kompletterande dokument</option>{data.documents.filter(d=>d.id!==documentId&&d.state==='active').map(d=><option key={d.id} value={d.id}>{d.file_name}</option>)}</select></label></div>
        {replaces&&<button type="button" className={button} onClick={()=>void compare()}>Jämför poster före aktivering</button>}
        {comparison&&<div className="rounded border bg-white p-3 text-sm"><p className="font-semibold">{(['added','changed','removed','unchanged','ambiguous'] as const).map(k=>`${{added:'Nya',changed:'Ändrade',removed:'Borttagna',unchanged:'Oförändrade',ambiguous:'Otydliga'}[k]}: ${comparison.filter(d=>d.kind===k).length}`).join(' · ')}</p><details className="mt-2"><summary>Visa förändringar</summary><ul className="max-h-64 overflow-auto">{comparison.filter(d=>d.kind!=='unchanged').map(d=><li key={d.key}>{d.post} — {{added:'Ny',removed:'Borttagen',changed:'Ändrad',ambiguous:'Flera poster med samma identitet',unchanged:'Oförändrad'}[d.kind]}</li>)}</ul></details><p className="mt-2 text-amber-900">Tidigare produktval sparas i historiken. Alla poster i den nya revisionen granskas på nytt, även om texten är oförändrad.</p></div>}
        <button type="button" className={button} disabled={Boolean(replaces&&!comparison)||busy} onClick={()=>void mutate({action:'document',documentId,revision:selected.revision,payload:{role,revision_label:label,replaces_document_id:replaces||null}}).then(ok=>{if(ok){setDocumentId('');setComparison(null);}})}>Spara roll och aktivera dokument</button>
      </fieldset></div>}
    </>}
    {notice&&<p role="status" className="text-sm text-emerald-800">{notice}</p>}
  </section>;
}
