// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/review" | "/company" | "/dashboard" | "/intelligence" | "/news" | "/partners" | "/products" | "/profile" | "/projects/demo" | "/projects/demo/analysis" | "/projects/demo/material-list" | "/projects/demo/product-resolution" | "/projects/demo/upload" | "/projects/new" | "/settings"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/pdf-extractor/extract" | "/api/pkms/import-json" | "/api/pkms/import-pdf" | "/api/pkms/products" | "/api/pkms/review-queue" | "/api/pkms/review-queue/approve" | "/api/projects"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/company" | "/dashboard" | "/intelligence" | "/news" | "/partners" | "/products" | "/profile" | "/projects" | "/settings"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/review": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/pdf-extractor/extract": {}
  "/api/pkms/import-json": {}
  "/api/pkms/import-pdf": {}
  "/api/pkms/products": {}
  "/api/pkms/review-queue": {}
  "/api/pkms/review-queue/approve": {}
  "/api/projects": {}
  "/company": {}
  "/dashboard": {}
  "/intelligence": {}
  "/news": {}
  "/partners": {}
  "/products": {}
  "/profile": {}
  "/projects": {}
  "/projects/demo": {}
  "/projects/demo/analysis": {}
  "/projects/demo/material-list": {}
  "/projects/demo/product-resolution": {}
  "/projects/demo/upload": {}
  "/projects/new": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/company": never
  "/dashboard": never
  "/intelligence": never
  "/news": never
  "/partners": never
  "/products": never
  "/profile": never
  "/projects": never
  "/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
