// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/review">> = Specific
  const handler = {} as typeof import("../../src/app/admin/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company">> = Specific
  const handler = {} as typeof import("../../src/app/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../src/app/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../src/app/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/demo/analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/demo/analysis">> = Specific
  const handler = {} as typeof import("../../src/app/projects/demo/analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/demo/material-list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/demo/material-list">> = Specific
  const handler = {} as typeof import("../../src/app/projects/demo/material-list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/demo">> = Specific
  const handler = {} as typeof import("../../src/app/projects/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/demo/product-resolution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/demo/product-resolution">> = Specific
  const handler = {} as typeof import("../../src/app/projects/demo/product-resolution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/demo/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/demo/upload">> = Specific
  const handler = {} as typeof import("../../src/app/projects/demo/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/new">> = Specific
  const handler = {} as typeof import("../../src/app/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pdf-extractor/extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pdf-extractor/extract">> = Specific
  const handler = {} as typeof import("../../src/app/api/pdf-extractor/extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pkms/import-json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pkms/import-json">> = Specific
  const handler = {} as typeof import("../../src/app/api/pkms/import-json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pkms/import-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pkms/import-pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/pkms/import-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pkms/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pkms/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/pkms/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pkms/review-queue/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pkms/review-queue/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/pkms/review-queue/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pkms/review-queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pkms/review-queue">> = Specific
  const handler = {} as typeof import("../../src/app/api/pkms/review-queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/company/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/company">> = Specific
  const handler = {} as typeof import("../../src/app/company/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/intelligence/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/intelligence/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/news/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/news">> = Specific
  const handler = {} as typeof import("../../src/app/news/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/partners/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../src/app/partners/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/projects/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/projects/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
