begin;

create or replace function public.normalize_sprsok_identity(value text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select lower(regexp_replace(btrim(coalesce(value, '')), '[[:space:]]+', ' ', 'g'));
$$;

create or replace function public.normalize_sprsok_article(value text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select upper(regexp_replace(btrim(coalesce(value, '')), '[[:space:]_./-]+', '', 'g'));
$$;

create table if not exists public.sprsok_products (
  id bigint generated by default as identity primary key,
  sin text,
  leverandor text,
  type text,
  utforelse text,
  k_verdi text,
  rti text,
  datablad text
);

alter table public.sprsok_products
  add column if not exists source text not null default 'sprsok',
  add column if not exists source_record_key text,
  add column if not exists external_product_id text,
  add column if not exists supplier text,
  add column if not exists manufacturer_article_number text,
  add column if not exists product_name text,
  add column if not exists variant text,
  add column if not exists category text,
  add column if not exists source_status text not null default 'active',
  add column if not exists last_synced_at timestamptz,
  add column if not exists source_data jsonb not null default '{}'::jsonb,
  add column if not exists import_metadata jsonb not null default '{}'::jsonb,
  add column if not exists manual_locked_fields text[] not null default '{}'::text[],
  add column if not exists validation_errors text[] not null default '{}'::text[],
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

update public.sprsok_products
set supplier = coalesce(supplier, leverandor),
    manufacturer_article_number = coalesce(manufacturer_article_number, sin),
    product_name = coalesce(product_name, type),
    variant = coalesce(variant, utforelse),
    external_product_id = coalesce(nullif(external_product_id, ''), id::text),
    last_synced_at = coalesce(last_synced_at, now()),
    source_record_key = coalesce(
      nullif(source_record_key, ''),
      'id:' || public.normalize_sprsok_identity(
        coalesce(nullif(external_product_id, ''), id::text)
      )
    );

alter table public.sprsok_products
  alter column source_record_key set not null;

create unique index if not exists sprsok_products_source_record_key_uidx
  on public.sprsok_products (source, source_record_key);
create index if not exists sprsok_products_external_id_idx
  on public.sprsok_products (source, external_product_id);
create index if not exists sprsok_products_article_idx
  on public.sprsok_products (source, manufacturer_article_number);

create table if not exists public.sprsok_sync_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'sprsok' check (source = 'sprsok'),
  status text not null check (status in ('running','paused','completed','failed')),
  dry_run boolean not null default false,
  checkpoint jsonb not null default '{"cursor":null,"offset":0,"pageNumber":1}'::jsonb,
  source_total integer,
  pages_received integer not null default 0,
  records_received integer not null default 0,
  accepted_count integer not null default 0,
  rejected_count integer not null default 0,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  unchanged_count integer not null default 0,
  review_count integer not null default 0,
  error_count integer not null default 0,
  datasheet_queue_error_count integer not null default 0,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists sprsok_sync_runs_latest_idx
  on public.sprsok_sync_runs (source, started_at desc);

create table if not exists public.sprsok_sync_page_logs (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.sprsok_sync_runs(id) on delete cascade,
  page_number integer not null,
  cursor text,
  offset_value integer not null default 0,
  records_received integer not null,
  next_cursor text,
  next_offset integer,
  source_total integer,
  received_at timestamptz not null default now(),
  unique (run_id, page_number)
);

create table if not exists public.sprsok_sync_errors (
  id bigint generated by default as identity primary key,
  run_id uuid references public.sprsok_sync_runs(id) on delete set null,
  error_scope text not null check (error_scope in ('page','product','datasheet','reconcile','index')),
  source_record_key text,
  checkpoint jsonb not null default '{}'::jsonb,
  error_message text not null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists sprsok_sync_errors_unresolved_idx
  on public.sprsok_sync_errors (created_at desc) where resolved_at is null;

create table if not exists public.sprsok_source_snapshot (
  run_id uuid not null references public.sprsok_sync_runs(id) on delete cascade,
  source_record_key text not null,
  external_product_id text,
  supplier text,
  manufacturer_article_number text,
  product_name text,
  variant text,
  validation_errors text[] not null default '{}'::text[],
  source_data jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now(),
  primary key (run_id, source_record_key)
);

create table if not exists public.sprsok_review_queue (
  id uuid primary key default gen_random_uuid(),
  product_id bigint references public.sprsok_products(id) on delete set null,
  source_record_key text not null unique,
  external_product_id text,
  supplier text,
  manufacturer_article_number text,
  variant text,
  validation_errors text[] not null default '{}'::text[],
  source_data jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected','resolved')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  review_note text
);

create table if not exists public.sprsok_datasheet_discovery_queue (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.sprsok_products(id) on delete cascade,
  source_record_key text not null,
  status text not null default 'pending'
    check (status in ('pending','processing','found','not_found','failed')),
  attempt_count integer not null default 0,
  last_error text,
  queued_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id)
);

create table if not exists public.sprsok_product_search_index (
  product_id bigint primary key references public.sprsok_products(id) on delete cascade,
  source_record_key text not null unique,
  normalized_article_number text not null default '',
  search_document text not null default '',
  is_visible boolean not null default false,
  hidden_reason text,
  indexed_at timestamptz not null default now()
);

create index if not exists sprsok_search_document_idx
  on public.sprsok_product_search_index using gin (to_tsvector('simple', search_document));
create index if not exists sprsok_search_article_idx
  on public.sprsok_product_search_index (normalized_article_number);

create or replace function public.refresh_sprsok_product_search_index()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  visible boolean;
  reason text;
begin
  visible := new.source_status not in ('inactive', 'deleted')
    and nullif(btrim(new.sin), '') is not null
    and nullif(btrim(new.leverandor), '') is not null
    and nullif(btrim(new.type), '') is not null
    and cardinality(new.validation_errors) = 0;
  reason := case
    when new.source_status in ('inactive', 'deleted') then 'source_status_' || new.source_status
    when nullif(btrim(new.sin), '') is null then 'missing_article_number'
    when nullif(btrim(new.leverandor), '') is null then 'missing_supplier'
    when nullif(btrim(new.type), '') is null then 'missing_product_name'
    when cardinality(new.validation_errors) > 0 then array_to_string(new.validation_errors, ',')
    else null
  end;

  insert into public.sprsok_product_search_index (
    product_id,
    source_record_key,
    normalized_article_number,
    search_document,
    is_visible,
    hidden_reason,
    indexed_at
  ) values (
    new.id,
    new.source_record_key,
    public.normalize_sprsok_article(new.sin),
    lower(concat_ws(' ', new.sin, new.leverandor, new.type, new.utforelse, new.k_verdi, new.rti)),
    visible,
    reason,
    now()
  )
  on conflict (product_id) do update
    set source_record_key = excluded.source_record_key,
        normalized_article_number = excluded.normalized_article_number,
        search_document = excluded.search_document,
        is_visible = excluded.is_visible,
        hidden_reason = excluded.hidden_reason,
        indexed_at = excluded.indexed_at;
  return new;
end;
$$;

drop trigger if exists refresh_sprsok_product_search_index_trigger
  on public.sprsok_products;
create trigger refresh_sprsok_product_search_index_trigger
after insert or update of
  source_record_key, sin, leverandor, type, utforelse, k_verdi, rti,
  source_status, validation_errors
on public.sprsok_products
for each row execute function public.refresh_sprsok_product_search_index();

insert into public.sprsok_product_search_index (
  product_id, source_record_key, normalized_article_number, search_document,
  is_visible, hidden_reason, indexed_at
)
select
  product.id,
  product.source_record_key,
  public.normalize_sprsok_article(product.sin),
  lower(concat_ws(' ', product.sin, product.leverandor, product.type, product.utforelse, product.k_verdi, product.rti)),
  product.source_status not in ('inactive', 'deleted')
    and nullif(btrim(product.sin), '') is not null
    and nullif(btrim(product.leverandor), '') is not null
    and nullif(btrim(product.type), '') is not null
    and cardinality(product.validation_errors) = 0,
  case
    when product.source_status in ('inactive', 'deleted') then 'source_status_' || product.source_status
    when nullif(btrim(product.sin), '') is null then 'missing_article_number'
    when nullif(btrim(product.leverandor), '') is null then 'missing_supplier'
    when nullif(btrim(product.type), '') is null then 'missing_product_name'
    when cardinality(product.validation_errors) > 0 then array_to_string(product.validation_errors, ',')
    else null
  end,
  now()
from public.sprsok_products product
on conflict (product_id) do update
set source_record_key = excluded.source_record_key,
    normalized_article_number = excluded.normalized_article_number,
    search_document = excluded.search_document,
    is_visible = excluded.is_visible,
    hidden_reason = excluded.hidden_reason,
    indexed_at = excluded.indexed_at;

create or replace view public.sprsok_product_search
with (security_invoker = true)
as
select
  product.id,
  product.sin,
  product.leverandor,
  product.type,
  product.utforelse,
  product.k_verdi,
  product.rti,
  product.datablad,
  product.source_record_key,
  product.external_product_id,
  product.source_status,
  index.normalized_article_number,
  index.search_document,
  index.indexed_at
from public.sprsok_products product
join public.sprsok_product_search_index index on index.product_id = product.id
where index.is_visible;

create or replace function public.begin_sprsok_sync(
  p_resume boolean default false,
  p_dry_run boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  selected_run public.sprsok_sync_runs%rowtype;
begin
  if p_resume then
    select * into selected_run
    from public.sprsok_sync_runs
    where source = 'sprsok' and status in ('paused', 'failed') and dry_run = p_dry_run
    order by updated_at desc
    limit 1
    for update skip locked;
  end if;
  if selected_run.id is null then
    insert into public.sprsok_sync_runs (status, dry_run)
    values ('running', p_dry_run)
    returning * into selected_run;
  else
    update public.sprsok_sync_runs
      set status = 'running', completed_at = null, updated_at = now()
    where id = selected_run.id
    returning * into selected_run;
  end if;
  return jsonb_build_object(
    'runId', selected_run.id,
    'checkpoint', selected_run.checkpoint,
    'counts', jsonb_build_object(
      'sourceTotal', selected_run.source_total,
      'pages', selected_run.pages_received,
      'received', selected_run.records_received,
      'accepted', selected_run.accepted_count,
      'rejected', selected_run.rejected_count,
      'created', selected_run.created_count,
      'updated', selected_run.updated_count,
      'unchanged', selected_run.unchanged_count,
      'review', selected_run.review_count,
      'errors', selected_run.error_count,
      'datasheetQueueErrors', selected_run.datasheet_queue_error_count
    )
  );
end;
$$;

create or replace function public.upsert_sprsok_product(
  p_run_id uuid,
  p_record jsonb,
  p_dry_run boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  record_key text := nullif(p_record ->> 'source_record_key', '');
  existing public.sprsok_products%rowtype;
  saved public.sprsok_products%rowtype;
  errors text[] := coalesce(
    array(select jsonb_array_elements_text(coalesce(p_record -> 'validation_errors', '[]'::jsonb))),
    '{}'::text[]
  );
  outcome text;
begin
  if record_key is null then
    record_key := 'invalid:' || md5(p_record::text);
  end if;

  insert into public.sprsok_source_snapshot (
    run_id, source_record_key, external_product_id, supplier,
    manufacturer_article_number, product_name, variant, validation_errors, source_data
  ) values (
    p_run_id, record_key, p_record ->> 'external_product_id', p_record ->> 'supplier',
    p_record ->> 'manufacturer_article_number', p_record ->> 'product_name',
    p_record ->> 'variant', errors, coalesce(p_record -> 'source_data', '{}'::jsonb)
  ) on conflict (run_id, source_record_key) do update
    set source_data = excluded.source_data,
        validation_errors = excluded.validation_errors,
        observed_at = now();

  if nullif(p_record ->> 'source_record_key', '') is null then
    if not p_dry_run then
      insert into public.sprsok_review_queue (
        source_record_key, external_product_id, supplier,
        manufacturer_article_number, variant, validation_errors, source_data
      ) values (
        record_key, p_record ->> 'external_product_id', p_record ->> 'supplier',
        p_record ->> 'manufacturer_article_number', p_record ->> 'variant',
        errors, coalesce(p_record -> 'source_data', '{}'::jsonb)
      ) on conflict (source_record_key) do update
        set validation_errors = excluded.validation_errors,
            source_data = excluded.source_data,
            status = 'pending',
            last_seen_at = now();
    end if;
    return jsonb_build_object('outcome', 'review');
  end if;

  select * into existing
  from public.sprsok_products
  where source = 'sprsok' and source_record_key = record_key;

  if existing.id is null then
    outcome := case when cardinality(errors) > 0 then 'review' else 'created' end;
  elsif existing.source_data = coalesce(p_record -> 'source_data', '{}'::jsonb)
    and existing.validation_errors = errors then
    outcome := case when cardinality(errors) > 0 then 'review' else 'unchanged' end;
  else
    outcome := case when cardinality(errors) > 0 then 'review' else 'updated' end;
  end if;
  if p_dry_run then return jsonb_build_object('outcome', outcome); end if;

  insert into public.sprsok_products (
    source, source_record_key, external_product_id, supplier,
    manufacturer_article_number, product_name, variant, category, source_status,
    sin, leverandor, type, utforelse, k_verdi, rti, datablad,
    last_synced_at, source_data, import_metadata, validation_errors
  ) values (
    'sprsok', record_key, p_record ->> 'external_product_id', p_record ->> 'supplier',
    p_record ->> 'manufacturer_article_number', p_record ->> 'product_name',
    p_record ->> 'variant', p_record ->> 'category', coalesce(p_record ->> 'source_status', 'active'),
    p_record ->> 'sin', p_record ->> 'leverandor', p_record ->> 'type',
    p_record ->> 'utforelse', p_record ->> 'k_verdi', p_record ->> 'rti', p_record ->> 'datablad',
    now(), coalesce(p_record -> 'source_data', '{}'::jsonb),
    jsonb_build_object('last_run_id', p_run_id), errors
  )
  on conflict (source, source_record_key) do update set
    external_product_id = case when 'external_product_id' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.external_product_id else excluded.external_product_id end,
    supplier = case when 'supplier' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.supplier else excluded.supplier end,
    manufacturer_article_number = case when 'manufacturer_article_number' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.manufacturer_article_number else excluded.manufacturer_article_number end,
    product_name = case when 'product_name' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.product_name else excluded.product_name end,
    variant = case when 'variant' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.variant else excluded.variant end,
    category = case when 'category' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.category else excluded.category end,
    source_status = excluded.source_status,
    sin = case when 'sin' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.sin else excluded.sin end,
    leverandor = case when 'leverandor' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.leverandor else excluded.leverandor end,
    type = case when 'type' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.type else excluded.type end,
    utforelse = case when 'utforelse' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.utforelse else excluded.utforelse end,
    k_verdi = case when 'k_verdi' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.k_verdi else excluded.k_verdi end,
    rti = case when 'rti' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.rti else excluded.rti end,
    datablad = case when 'datablad' = any(public.sprsok_products.manual_locked_fields)
      then public.sprsok_products.datablad else excluded.datablad end,
    last_synced_at = now(),
    source_data = excluded.source_data,
    import_metadata = public.sprsok_products.import_metadata || excluded.import_metadata,
    validation_errors = excluded.validation_errors,
    updated_at = now()
  returning * into saved;

  if cardinality(errors) > 0 then
    insert into public.sprsok_review_queue (
      product_id, source_record_key, external_product_id, supplier,
      manufacturer_article_number, variant, validation_errors, source_data
    ) values (
      saved.id, record_key, saved.external_product_id, saved.supplier,
      saved.manufacturer_article_number, saved.variant, errors, saved.source_data
    ) on conflict (source_record_key) do update
      set product_id = excluded.product_id,
          validation_errors = excluded.validation_errors,
          source_data = excluded.source_data,
          status = 'pending',
          last_seen_at = now();
  end if;
  return jsonb_build_object('outcome', outcome, 'productId', saved.id);
end;
$$;

create or replace function public.queue_sprsok_datasheet(
  p_run_id uuid,
  p_source_record_key text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare selected_product public.sprsok_products%rowtype;
begin
  select * into selected_product from public.sprsok_products
  where source = 'sprsok' and source_record_key = p_source_record_key;
  if selected_product.id is null or nullif(selected_product.datablad, '') is not null then return; end if;
  insert into public.sprsok_datasheet_discovery_queue (product_id, source_record_key)
  values (selected_product.id, selected_product.source_record_key)
  on conflict (product_id) do update
    set status = case
      when public.sprsok_datasheet_discovery_queue.status in ('found', 'processing')
      then public.sprsok_datasheet_discovery_queue.status else 'pending' end,
        updated_at = now();
end;
$$;

create or replace function public.record_sprsok_sync_page(
  p_run_id uuid,
  p_checkpoint jsonb,
  p_received integer,
  p_next_checkpoint jsonb,
  p_source_total integer default null
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  insert into public.sprsok_sync_page_logs (
    run_id, page_number, cursor, offset_value, records_received,
    next_cursor, next_offset, source_total
  ) values (
    p_run_id, coalesce((p_checkpoint ->> 'pageNumber')::integer, 1),
    p_checkpoint ->> 'cursor', coalesce((p_checkpoint ->> 'offset')::integer, 0),
    p_received, p_next_checkpoint ->> 'cursor',
    (p_next_checkpoint ->> 'offset')::integer, p_source_total
  ) on conflict (run_id, page_number) do update
    set records_received = excluded.records_received,
        next_cursor = excluded.next_cursor,
        next_offset = excluded.next_offset,
        source_total = excluded.source_total,
        received_at = now();
  update public.sprsok_sync_runs
  set checkpoint = coalesce(p_next_checkpoint, p_checkpoint),
      source_total = coalesce(p_source_total, source_total),
      pages_received = pages_received + 1,
      records_received = records_received + p_received,
      updated_at = now()
  where id = p_run_id;
end;
$$;

create or replace function public.record_sprsok_sync_error(
  p_run_id uuid,
  p_scope text,
  p_source_record_key text,
  p_checkpoint jsonb,
  p_error_message text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  insert into public.sprsok_sync_errors (
    run_id, error_scope, source_record_key, checkpoint, error_message
  ) values (
    p_run_id, p_scope, p_source_record_key, coalesce(p_checkpoint, '{}'::jsonb),
    left(coalesce(p_error_message, 'Unknown error'), 2000)
  );
end;
$$;

create or replace function public.finish_sprsok_sync(
  p_run_id uuid,
  p_status text,
  p_checkpoint jsonb,
  p_counts jsonb
)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  if p_status not in ('completed', 'paused', 'failed') then
    raise exception 'Invalid Sprsok sync status';
  end if;
  update public.sprsok_sync_runs set
    status = p_status,
    checkpoint = coalesce(p_checkpoint, checkpoint),
    source_total = coalesce((p_counts ->> 'sourceTotal')::integer, source_total),
    pages_received = coalesce((p_counts ->> 'pages')::integer, pages_received),
    records_received = coalesce((p_counts ->> 'received')::integer, records_received),
    accepted_count = coalesce((p_counts ->> 'accepted')::integer, accepted_count),
    rejected_count = coalesce((p_counts ->> 'rejected')::integer, rejected_count),
    created_count = coalesce((p_counts ->> 'created')::integer, created_count),
    updated_count = coalesce((p_counts ->> 'updated')::integer, updated_count),
    unchanged_count = coalesce((p_counts ->> 'unchanged')::integer, unchanged_count),
    review_count = coalesce((p_counts ->> 'review')::integer, review_count),
    error_count = coalesce((p_counts ->> 'errors')::integer, error_count),
    datasheet_queue_error_count = coalesce((p_counts ->> 'datasheetQueueErrors')::integer, datasheet_queue_error_count),
    completed_at = case when p_status in ('completed', 'failed') then now() else null end,
    updated_at = now()
  where id = p_run_id;
end;
$$;

create or replace function public.reindex_sprsok_products(
  p_source_record_keys text[] default null,
  p_dry_run boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare candidate_count integer;
begin
  select count(*) into candidate_count
  from public.sprsok_products
  where source = 'sprsok'
    and (p_source_record_keys is null or source_record_key = any(p_source_record_keys));
  if p_dry_run then
    return jsonb_build_object('candidates', candidate_count, 'indexed', 0);
  end if;

  insert into public.sprsok_product_search_index (
    product_id, source_record_key, normalized_article_number, search_document,
    is_visible, hidden_reason, indexed_at
  )
  select
    product.id, product.source_record_key, public.normalize_sprsok_article(product.sin),
    lower(concat_ws(' ', product.sin, product.leverandor, product.type, product.utforelse, product.k_verdi, product.rti)),
    product.source_status not in ('inactive', 'deleted')
      and nullif(btrim(product.sin), '') is not null
      and nullif(btrim(product.leverandor), '') is not null
      and nullif(btrim(product.type), '') is not null
      and cardinality(product.validation_errors) = 0,
    case
      when product.source_status in ('inactive', 'deleted') then 'source_status_' || product.source_status
      when nullif(btrim(product.sin), '') is null then 'missing_article_number'
      when nullif(btrim(product.leverandor), '') is null then 'missing_supplier'
      when nullif(btrim(product.type), '') is null then 'missing_product_name'
      when cardinality(product.validation_errors) > 0 then array_to_string(product.validation_errors, ',')
      else null
    end,
    now()
  from public.sprsok_products product
  where product.source = 'sprsok'
    and (p_source_record_keys is null or product.source_record_key = any(p_source_record_keys))
  on conflict (product_id) do update set
    source_record_key = excluded.source_record_key,
    normalized_article_number = excluded.normalized_article_number,
    search_document = excluded.search_document,
    is_visible = excluded.is_visible,
    hidden_reason = excluded.hidden_reason,
    indexed_at = excluded.indexed_at;
  return jsonb_build_object('candidates', candidate_count, 'indexed', candidate_count);
end;
$$;

create or replace view public.sprsok_reconciliation_issues
with (security_invoker = true)
as
with latest_complete_run as (
  select id from public.sprsok_sync_runs
  where source = 'sprsok' and status = 'completed' and not dry_run
  order by completed_at desc nulls last limit 1
)
select
  'missing_database'::text as issue_type,
  snapshot.source_record_key,
  null::bigint as product_id,
  snapshot.external_product_id,
  snapshot.supplier,
  snapshot.manufacturer_article_number,
  snapshot.variant,
  'Source product is missing in database.'::text as reason,
  snapshot.run_id,
  snapshot.observed_at as detected_at
from public.sprsok_source_snapshot snapshot
join latest_complete_run latest on latest.id = snapshot.run_id
left join public.sprsok_products product
  on product.source = 'sprsok' and product.source_record_key = snapshot.source_record_key
where product.id is null
union all
select
  'missing_index', product.source_record_key, product.id, product.external_product_id,
  product.leverandor, product.sin, product.utforelse,
  'Database product is missing in search index.', null, now()
from public.sprsok_products product
left join public.sprsok_product_search_index index on index.product_id = product.id
where product.source = 'sprsok' and index.product_id is null
union all
select
  'hidden_filter', product.source_record_key, product.id, product.external_product_id,
  product.leverandor, product.sin, product.utforelse,
  coalesce(index.hidden_reason, 'Hidden by search visibility rule.'), null, index.indexed_at
from public.sprsok_products product
join public.sprsok_product_search_index index on index.product_id = product.id
where product.source = 'sprsok' and not index.is_visible
union all
select
  'failed_import', error.source_record_key, null, null, null, null, null,
  error.error_message, error.run_id, error.created_at
from public.sprsok_sync_errors error
where error.resolved_at is null and error.error_scope in ('product','reconcile','index');

alter table public.sprsok_products enable row level security;
alter table public.sprsok_sync_runs enable row level security;
alter table public.sprsok_sync_page_logs enable row level security;
alter table public.sprsok_sync_errors enable row level security;
alter table public.sprsok_source_snapshot enable row level security;
alter table public.sprsok_review_queue enable row level security;
alter table public.sprsok_datasheet_discovery_queue enable row level security;
alter table public.sprsok_product_search_index enable row level security;

drop policy if exists sprsok_products_authenticated_read on public.sprsok_products;
create policy sprsok_products_authenticated_read on public.sprsok_products
for select to authenticated using (
  exists (
    select 1 from public.sprsok_product_search_index search_index
    where search_index.product_id = sprsok_products.id
      and search_index.is_visible
  )
);

drop policy if exists sprsok_search_index_authenticated_read
  on public.sprsok_product_search_index;
create policy sprsok_search_index_authenticated_read
on public.sprsok_product_search_index
for select to authenticated using (is_visible);

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'sprsok_sync_runs', 'sprsok_sync_page_logs', 'sprsok_sync_errors',
    'sprsok_source_snapshot', 'sprsok_review_queue',
    'sprsok_datasheet_discovery_queue', 'sprsok_product_search_index'
  ] loop
    execute format('drop policy if exists sprsok_platform_admin_all on public.%I', table_name);
    execute format(
      'create policy sprsok_platform_admin_all on public.%I for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin())',
      table_name
    );
  end loop;
end;
$$;

revoke all on function public.begin_sprsok_sync(boolean, boolean) from public, anon, authenticated;
revoke all on function public.upsert_sprsok_product(uuid, jsonb, boolean) from public, anon, authenticated;
revoke all on function public.queue_sprsok_datasheet(uuid, text) from public, anon, authenticated;
revoke all on function public.record_sprsok_sync_page(uuid, jsonb, integer, jsonb, integer) from public, anon, authenticated;
revoke all on function public.record_sprsok_sync_error(uuid, text, text, jsonb, text) from public, anon, authenticated;
revoke all on function public.finish_sprsok_sync(uuid, text, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.reindex_sprsok_products(text[], boolean) from public, anon, authenticated;

grant execute on function public.begin_sprsok_sync(boolean, boolean) to service_role;
grant execute on function public.upsert_sprsok_product(uuid, jsonb, boolean) to service_role;
grant execute on function public.queue_sprsok_datasheet(uuid, text) to service_role;
grant execute on function public.record_sprsok_sync_page(uuid, jsonb, integer, jsonb, integer) to service_role;
grant execute on function public.record_sprsok_sync_error(uuid, text, text, jsonb, text) to service_role;
grant execute on function public.finish_sprsok_sync(uuid, text, jsonb, jsonb) to service_role;
grant execute on function public.reindex_sprsok_products(text[], boolean) to service_role;

grant select on public.sprsok_product_search to authenticated, service_role;
grant select on public.sprsok_reconciliation_issues to service_role;
revoke select on public.sprsok_products from anon, authenticated;
grant select (
  id, sin, leverandor, type, utforelse, k_verdi, rti, datablad,
  source_record_key, external_product_id, source_status
) on public.sprsok_products to authenticated;
revoke select on public.sprsok_product_search_index from anon, authenticated;
grant select (
  product_id, source_record_key, normalized_article_number,
  search_document, is_visible, hidden_reason, indexed_at
) on public.sprsok_product_search_index to authenticated;
grant select, insert, update, delete on
  public.sprsok_products,
  public.sprsok_sync_runs,
  public.sprsok_sync_page_logs,
  public.sprsok_sync_errors,
  public.sprsok_source_snapshot,
  public.sprsok_review_queue,
  public.sprsok_datasheet_discovery_queue,
  public.sprsok_product_search_index
to service_role;

commit;
