/** Read-only explanation of the audited engine, never executable customer configuration. */
export const RULE_CATALOG_VERSION = "ahlsell-product-rules-2026-09-27.6";
export const RULE_CATALOG_DATE = "27 september 2026";

export type RuleKind = "requirement" | "search" | "ranking" | "review" | "assumption" | "gap";
export const RULE_KIND_LABELS: Record<RuleKind, string> = {
  requirement: "Tekniskt krav", search: "Sökning & urval", ranking: "Poäng & ordning",
  review: "Manuell kontroll", assumption: "Fast antagande", gap: "Kontroll saknas"
};
export type RuleExample = { input: string; result: string };
export type MatchingRule = {
  id: string; title: string; when: string; result: string;
  kind?: RuleKind; notes?: string[]; example?: RuleExample;
  table?: { columns: string[]; rows: string[][] };
};
export type RuleGroup = {
  id: string; title: string; appliesTo: string; description: string;
  kind: RuleKind; sources: string[]; rules: MatchingRule[];
};
const rule = (id: string, title: string, when: string, result: string, extra: Partial<Omit<MatchingRule, "id" | "title" | "when" | "result">> = {}): MatchingRule => ({ id, title, when, result, ...extra });
const table = (columns: string[], rows: string[][]) => ({ columns, rows });

export const MATCHING_RULE_GROUPS: RuleGroup[] = [
  {
    id: "underlag", title: "PDF-postens underlag", appliesTo: "Alla produktposter", kind: "requirement",
    description: "Vilken text och vilka egenskaper som får styra produktvalet.",
    sources: ["requirement-snapshot.ts", "ahlsell-requirement-context.ts", "ahlsell-requirement-intent.ts"],
    rules: [
      rule("sparat-underlag", "Samma sparade underlag i hela flödet", "En post visas, matchas, godkänns eller exporteras.", "Använd den sparade versionen av posten. Nya importer märks med extraktionsversion 1; äldre poster märks som version 0 vid läsning. Sidöppning tolkar inte om PDF-filen och ersätter inte sparade rättelser."),
      rule("egen-produkt", "Postens egen produkt går först", "Posten har en egen produktbeskrivning eller egna tekniska egenskaper.", "Använd dessa före äldre kategorier och delar som bara nämns som ingående tillbehör.", { example: { input: "Komplett rörledning inklusive böjar och kopplingar.", result: "Sök rör som huvudprodukt. Hantera böjar och kopplingar som ingående delar." } }),
      rule("huvudnamn", "Skilj huvudprodukt från ingående delar", "Produkttexten innehåller exempelvis med, inklusive, for eller til.", "Flera kontroller använder texten före dessa ord för att identifiera det som säljs. Ett tillbehör till en ventil ska inte bli en komplett ventil."),
      rule("arv", "Ärv krav från närmaste huvudpost", "En underpost innehåller exempelvis endast DN50.", "Närmaste huvudposts rubrik får hjälpa till. Egna egenskaper går först; godtyckliga äldre rubriker får inte bli produktkrav.", { notes: ["Teknisk text begränsas till de sista relevanta UNDERPOST-blocken, högst två. Vid saknad huvudpost begränsas arvet ytterligare.", "Tillåtna äldre tekniska egenskaper omfattar material, kvalitet, skarv, tryck, dimension, K, respons, temperatur, finish och system/utförande."] }),
      rule("generella-rorkrav", "Läs generella rörbestämmelser separat", "Underlaget innehåller generella krav på rör och rördelar.", "Läs igenkända krav på galvanisering, tillåtna skarvar och förbud mot presskopplingar. Kapitel, plats och dokumentationsprosa blir inte automatiskt artikeldata."),
      rule("pdf-kommentar", "PDF-kommentar är en sökhänvisning", "PDF-kommentaren innehåller ett NRF-nummer eller kompletterande krav.", "Numret kan styra sökningen men ersätter inte tekniska kontroller. Villkor utöver en ren artikelhänvisning kan kräva manuell granskning.", { kind: "search" }),
      rule("text-normalisering", "Normalisera språk och skrivsätt", "Krav eller produkttext skrivs med olika skiftläge, nordiska tecken eller skiljetecken.", "Normalisera texten och använd kända svenska, norska och engelska synonymer. Detta innebär inte att all fritext förstås automatiskt."),
      rule("pdf-varningar", "Behåll osäkerhet i PDF-underlaget", "Läsningen har varningar eller kravprofilen innehåller motstridiga värden.", "För vidare kontrollbehovet till produktbedömningen. Saknat eller motsägelsefullt underlag ska inte bli en säker match.", { kind: "review" })
    ]
  },
  {
    id: "produktgrupp", title: "Produktgrupp & posttyp", appliesTo: "Alla poster", kind: "search",
    description: "Hur Scipx väljer produktfamilj och klassificerar posterna i kapitelöversikten.",
    sources: ["requirement-discipline.ts", "ahlsell-requirement-intent.ts", "ahlsell-cable-trunking.ts", "ahlsell-functional-products.ts", "ahlsell-electrical-heating.ts", "ahlsell-generic-product-relevance.ts", "product-requirement-category.ts", "requirement-extraction-warnings.ts", "ns3420-product-classification.ts", "project-requirement-views.ts", "distributor-requirement-lines.ts"],
    rules: [
      rule("visad-produktgrupp", "Samma aktuella produktgrupp i tabell och kort", "Ett nytt eller tidigare importerat projekt visas.", "Beräkna produktgruppen från postens egen rubrik och NS-kod. El, ventilation, sanitet, pumpar och filter har egna grupper. En äldre VVS-kategori, kapiteltext, PDF-kommentar eller mängdenheten m får inte ensam avgöra gruppen.", { notes: ["Befintliga projekt får den aktuella visningsgruppen när de öppnas. Sparade krav, kommentarer, mängder och godkända produktval ändras inte.", "En okänd produkt visas i Övrig el och tele, Övrig ventilation, Övriga VVS-produkter eller Övriga produkter när en mer exakt grupp saknas.", "Den kompakta tabellöversikten och produktkortet använder samma klassificering. Produktgrupp ändrar inte indelningen i Produktposter, Rund Sum och Prosjekt information."], example: { input: "KABELPLATE · WC2.542A · äldre kategori Styrning och mätning", result: "Kabelstegar och kabelbärsystem i både tabell och produktkort." } }),
      rule("fack-fore-vvs", "Identifiera fack före VVS-regler", "Egen rubrik eller kod anger el eller ventilation.", "Använd produktspecifik sökning när familjen känns igen, annars postens eget produktnamn. En äldre rörkategori eller sprinklertext i kapitlet får inte styra sökningen. Den lokala VVS-katalogen används inte för dessa poster.", { example: {input:"KABELSTIGE · WC2.522A · 501,10 m",result:"Sök KABELSTIGE. Ingen ärvd sprinkler- eller DN-sökning."}, notes:["W/X-koder behandlas som el/tele och V-koder som ventilation. Detta ersätter inte en fullständig licensierad NS-databas.","Enheten m ensam gör aldrig en okänd produkt till ett rör."] }),
      rule("namngiven-familj", "Namngiven huvudprodukt styr familjen", "Texten anger exempelvis tryckvakt, manometer, aktuator, WC eller dusch.", "Välj den uttryckliga huvudprodukten före äldre kategorier eller utrustning som produkten ska anslutas till.", { notes: ["Rör, rördelar, ventiler, sprinkler, slang, mätare, pumpar, filter, skåp, sanitetsprodukter och flera andra familjer känns igen.", "En igenkänd grupp har inte nödvändigtvis lika omfattande tekniska kontroller som sprinklerhuvuden."] }),
      rule("dn-meter", "DN-post med meter blir normalt rör", "Posten beskriver en dimension och har enheten m.", "Välj rörfamiljen, så länge beskrivningen eller NS-koden inte uttryckligen anger slang eller rördel.", { example: { input: "DN50 · 126 m", result: "Sök rör i DN50. 126 m är mängden som ska köpas." } }),
      rule("slang-eget", "Sprinklerslang är en egen familj", "Texten anger sprinklerslang, flexislange, VicFlex eller motsvarande.", "Sök slang även om rubriken innehåller rørledning. Ett slangfäste eller en slangnippel ska inte bli huvudslangen.", { notes: ["En slangträff ger +65 och igenkänd sprinkleranknytning +10.", "Om föreskriven anslutnings-DN saknas ges −25 och varning, utöver övriga tillämpliga dimensionskontroller."] }),
      rule("vaggkanal", "Väggkanaler är en egen produktfamilj", "Posten beskriver en vägg-, kabel- eller installationskanal.", "Sök Veggkanal, Veggkanal aluminium när materialet anges och Installasjonskanal. Meter gör inte kanalen till rör och H×D blir inte DN.", { notes: ["En kanal eller kanalunderdel ger +65 familjepoäng. Lock, fronter, hörn och ändstycken utesluts som huvudprodukt.", "Verifiera höjd och djup, antal rum, montage och om lock och skiljeväggar ingår. Kanalträffen ensam är inte en verifierad match.", "Dokumenterad plast/PVC avviker från ett aluminiumkrav. Saknat material kräver kontroll.", "En tidigare okänd PDF-kategori ger inte längre okänd-familj-varning när kanalens namn identifieras. Övriga PDF-varningar behålls."] }),
      rule("skap-eget", "Fördelarskåp bedöms som komplett leverans", "Huvudprodukten är ett fördelarskåp.", "Behåll skåpet som huvudprodukt. Ingående ventiler och fördelare bedöms separat, och skåpmått blir inte rördimensioner."),
      rule("ns-mappning", "Använd särskild NS3420-mappning", "NS-koden omfattas av en inlagd produktfamiljsregel.", "Komplettera produktidentifieringen med koden och beskrivningen. Detta är ett begränsat urval, inte en fullständig NS3420-tolkning.", { table: table(["Kodprefix", "Familj"], [["UB1.3311", "Sprinklerslang"], ["UB1.3211", "Rör"], ["UB1.3111", "Rör när beskrivningen stödjer det och inte uttryckligen beskriver annan produkt"]]) }),
      rule("armatur-familj", "Sök armaturer med katalogens produktnamn", "Postens huvudprodukt är en belysningsarmatur.", "Sök Takarmatur med montage och DALI/LED när detta anges, samt Lysarmatur och LED armatur. Använd inte hela NS-rubriken som enda sökning.", { notes: ["Dimrar, lösa drivdon, fästen och nödljus utesluts som huvudprodukt för vanlig belysning.", "En armaturfamilj ger 55 poäng. Angivet infällt montage och DALI ger ytterligare 15 poäng vardera men artikelvarianten måste verifieras. Saknade uppgifter kräver kontroll. Mått, ljusflöde och optik är inte automatiskt verifierade.", "Downlight och plafond räknas som fel produkttyp när PDF-mått anger en långsmal armatur (längden mer än fyra gånger bredden)."] }),
      rule("energiventil-familj", "Energiventiler kräver rätt ventilfunktion", "Huvudprodukten eller ventiltypen anger energiventil eller regleringsventil.", "Sök Energiventil/Energy Valve eller Reguleringsventil/Innreguleringsventil med postens DN. Projektets komponentkod ingår inte i sökningen.", { notes: ["Energiventil är en egen familj. Klamrar, slangnipplar, vanliga avstängningsventiler och lösa ställdon är inte alternativ.", "Dimension och gänganslutning räcker inte som bevis för rätt produkttyp. Energimätning, sensorer, flöde och styrning måste också verifieras."] }),
      rule("elvarme-familj", "Elvärme använder typ, effekt och spänning", "PDF-posten anger elektrisk värmeovn eller värmekabel.", "Använd samma familj för kategorisering och matchning. Sök Panelovn eller Gjennomstrømningsovn enligt Type, med effekt och spänning. Värmekabel använder Elementtype och självreglering när det anges.", { notes: ["XC1/XC2 används tillsammans med postens egna typfält; detta är regler från granskade PDF-poster, inte en fullständig NS-databas.", "Familjen ger 55 poäng, entydig artikelstyrkt effekt 15 och spänning 10. Verktyg, adaptrar, bits och lösa tillbehör utesluts som huvudprodukt.", "Fel dokumenterad effekt eller spänning ger teknisk avvikelse. W, W/m och W/m² är olika krav. Saknat eller flertydigt underlag kräver kontroll.", "Endast artikelnamn, verifierad underrubrik och märkta tekniska fält styrker effekt/spänning. Familjebeskrivningar kan omfatta flera varianter och räcker inte.", "Kapslingsgrad, montage, anslutning, termostat och SD-styrning måste granskas. En familjeträff godkänner inte installationen."] }),
      rule("okand-familj", "Okänd produkt kräver granskning", "Ingen tydlig produktfamilj kan identifieras.", "Sök på postens egen beskrivning och markera att produktgruppen behöver fastställas. Den lokala katalogen ger inga förslag enbart på dimension eller material om varken produkttyp eller uttrycklig artikel/modell är identifierad. Automatiska Ahlsell-förslag kräver att produktnamnet innehåller postens identifierande produktord; allmänna ord som elektrisk, gemensamma tal eller träffar enbart i tillbehörsbeskrivningen räcker inte. Om identiteten saknas visas inga automatiska förslag. Manuell sökning behålls med avvikelsebedömning.", { kind: "review" }),
      rule("postflikar", "RS först, därefter mängd och enhet", "En post ska placeras i projektets översikt.", "RS går till Rund Sum. Produktposter kräver läsbar mängd ≥ 0 och en användbar mängdenhet, exempelvis m eller st. Övriga poster och informationsfragment går till Prosjekt information. Avvisade och ersatta poster visas inte.", { notes: ["Ett tal utan mängdenhet räcker inte. DN80 och 12 bar är tekniska krav, inte en mängdsättning.", "Inledande text som saknar föregående post i filen bevaras som information utan påhittat postnummer. Kända sidfortsättningar följer sin ursprungliga post.", "Alla posttyper visas tillsammans under PDF-kapitlet i källordning. Huvudpostens gemensamma krav följer också relevanta underposter.", "Alla tre posttyper kan öppnas för manuellt produktval. PDF-inläsningen omfattar alla kapitel, även utan sprinklerord."] }),
      rule("lokal-arbetspost", "Arbetsposter och projektinformation hoppar över lokal automatisk sökning", "Den interna postklassificeringen anger demontering, projektinformation eller arbetsmoment, exempelvis dokumentation eller håltagning.", "Den lokala automatiska MLDL-vägen ger inga kandidater. Offentlig eller manuell sökning kan fortfarande användas från produktkortet.")
    ]
  },
  {
    id: "sokning", title: "Sökning i MLDL & Ahlsell", appliesTo: "Automatiska produktförslag", kind: "search",
    description: "Sökkällor, sökfraser och hur stort urval som undersöks.",
    sources: ["ahlsell-shared-fetch.server.ts", "ahlsell-hybrid-matching.ts", "ahlsell-public-match.ts", "ahlsell-public-catalog.ts", "ahlsell-mldl-catalog.ts"],
    rules: [
      rule("tva-kataloger", "Kombinera MLDL och offentlig katalog", "Ett produktkort öppnas och Scipx söker huvudprodukt för den posten.", "Bedöm lokala MLDL-artiklar och komplettera med Ahlsells offentliga katalog. Offentliga och manuella produkter behöver inte finnas i MLDL.", { notes: ["Uppladdning, projektöversikt och öppning av PDF-kapitel startar inga sökningar mot Ahlsell. Sökning och hämtning av produkttexter sker bara för det öppna produktkortet.", "MLDL-urvalet filtreras på produktfamilj. Uttryckligt NRF eller modell kan också ta in en artikel i urvalet, men den måste fortfarande genomgå teknisk bedömning.", "Lokala osannolika kandidater tas bort innan de bästa 50 väljs."] }),
      rule("marknad", "Kravspråket väljer Ahlsell-marknad", "Underlaget innehåller norska tekniska ord.", "Sök normalt på ahlsell.no; annars ahlsell.se. Marknaden följer inte enbart kontots språk.", { kind: "assumption" }),
      rule("exakt-nrf", "Kontrollera ett ledande NRF separat", "PDF-kommentaren har ett artikelnummer, annars finns en lokal kandidat utan teknisk konflikt.", "Slå upp första kommentarsnumret eller den ledande lokala artikeln separat. Behåll endast resultat med samma normaliserade artikelnummer."),
      rule("tekniska-sokord", "Bygg sökfraser från egna egenskaper", "Produktfamilj och tekniska krav har identifierats.", "Sök med produktfamilj, relevanta dimensioner och andra igenkända egenskaper. Skicka sökord/NRF till Ahlsell, inte hela PDF-filen.", { table: table(["Familj", "Sökord"], [["Sprinklerhuvud", "K, QR/SR, upp/ned/vägg, temperatur, finish, torrt/öppet"], ["Sprinklerslang", "Sprinklerslange/Fleksibelslange/VicFlex och DN"], ["Rör", "Material, materialkvalitet, DN/Ø, SDR, skarv och PN"], ["Ventil", "Ventiltyp, DN, PN och övervakning"], ["Rördel", "Deltyp, anslutningar, dimension och skarv"], ["Övriga/okänd", "Produktens egna namn och igenkända egenskaper"]]) }),
      rule("matord-i-rubrik", "Mängdord i rubriken är inte sökord", "En generell produktrubrik slutar med exempelvis – LENGDE, – ANTALL eller – AREAL.", "Ta bort mätningssuffixet från katalogsökningen. PDF-rubriken, mängden och enheten behålls."),
      rule("mangd-inte-dimension", "Antal och meter är inte artikelns dimension", "Posten har en totalmängd i meter eller styck.", "Håll mängden separat från DN, Ø och produktens längd. Totalmängden används inte som dimension i sökningen.", { example: { input: "Rör DN25, mängd 132 m.", result: "Sök DN25-rör. Sök inte efter en artikel som är 132 meter lång." } }),
      rule("standard-massing", "Mässing är standard när sprinklerfinish saknas", "Ett sprinklerhuvud saknar finish och finishen är inte uttryckligen valfri.", "Använd mässing i sökguiden. Explicit vit, svart, krom eller annan igenkänd finish har företräde.", { kind: "assumption" }),
      rule("reservsokord", "Använd inlagda alternativa sökord", "Den vanliga familjesökningen behöver produktgruppens sökvarianter.", "Använd bland annat K160/K161/K162, manometer 0–16 bar, PS10 eller pumpfamiljernas termer. Sökordet är inte bevis för teknisk likvärdighet.", { kind: "assumption" }),
      rule("gemensam-anropsgrans", "Gemensam gräns mot Ahlsell", "Flera användare eller serverinstanser söker samtidigt.", "Dela en gräns på 6 pågående hämtningar och 120 nya anrop per minut. Identiska hämtningar delar vänteläge och ett kort svarscache på 2 minuter. Leverantörens 429 och serverfel ger gemensam väntetid.", {notes:["Vid full gräns kan sökningen behöva göras om. Lokala förslag behålls om de finns; ofullständig sökning betyder inte att varan saknas.","Cachen rymmer högst 64 komprimerade svar om högst 128 kB vardera.","Koordineringen ligger i databasen. Om den inte fungerar skickas inga nya leverantörsanrop."]}),
      rule("sokgranser", "Begränsa automatisk katalogsökning", "En automatisk huvudproduktsökning körs.", "Undersök ett begränsat urval. Hela Ahlsells sortiment och alla varianter granskas inte vid varje sökning.", { table: table(["Urval", "Gräns"], [["Sökfraser", "3, högst 180 tecken per fras"], ["Offentliga kandidater", "40 per sökfras"], ["Sidor", "2 per sökfras"], ["Variantfamiljer", "4, en bäst rankad variant per familj"], ["Produktsidor med detaljhämtning", "6; upp till 3 MLDL-artiklar prioriteras först"], ["Lokala MLDL-kandidater", "50 efter bedömning och sortering"]]) }),
      rule("familjeurval", "Försortera familjer innan detaljhämtning", "Sökningen har flera produktfamiljer.", "Prioritera rätt familj, särskiljande sökord och dimension. Dessa poäng används för urval, inte som slutlig matchningspoäng.", { kind: "ranking", table: table(["Signal", "Poäng"], [["Rätt familj", "+200"], ["Utesluten produkttyp", "−220"], ["Relevant ord i namn / övrig text", "+8 / +3 per ord"], ["Dimensionsord", "+15"]]), notes: ["Allmänna ord som sprinkler, med, for, mm och DN räknas inte som särskiljande ord i detta steg."] }),
      rule("varianturval", "Välj relevant artikelvariant", "En undersökt produktfamilj innehåller flera varianter.", "Prioritera exakt efterfrågat NRF eller bäst försorterad variant. Gör därefter den gemensamma tekniska bedömningen.", { kind: "ranking", table: table(["Egenskap", "Stämmer", "Avviker"], [["Aktiv / köpbar", "+2 / +1", "Ej köpbar −20"], ["K", "+30", "−100"], ["Temperatur", "+25", "−80"], ["Respons", "+20", "−60"], ["Färg", "+15", "−25"]]), notes: ["Saknat värde ger normalt noll i försorteringen men kan ge varning i slutbedömningen."] }),
      rule("cache-natverk", "Skilj sökfel från ingen träff", "Sökningen är avbruten, begränsad eller bara delvis lyckad.", "Behåll lokala förslag och ange ofullständig sökning. Dra inte slutsatsen att rätt artikel saknas hos Ahlsell.", { notes: ["Offentlig sökcache: 2 minuter. Kataloganrop: 8 sekunders timeout.", "Produktdetaljer cachelagras upp till 12 timmar; negativa svar 5 minuter."] })
    ]
  },
  {
    id: "bedomning", title: "Poäng & matchningsstatus", appliesTo: "Alla bedömda kandidater", kind: "ranking",
    description: "Vad som gör ett förslag rekommenderat, möjligt eller felaktigt.",
    sources: ["ahlsell-candidate-ranking.ts", "ahlsell-technical-conflicts.ts", "ahlsell-candidate-merge.ts", "ahlsell-mldl-catalog.ts"],
    rules: [
      rule("poang", "Poäng är inte sannolikhet", "Tekniska egenskaper och katalogsignaler ger plus- eller minuspoäng.", "Begränsa poängen till 0–100. Varningar och kontrollflaggor kan hindra verifiering även vid 100 poäng."),
      rule("rekommenderad", "Rekommenderad kräver minst 75 och inga varningar", "Kandidaten har minst 75 poäng, inga kvarstående varningar och inget olöst tillbehörskrav.", "Klassificera som rekommenderad. Detta är ett produktförslag och inte användarens godkännande.", { example: { input: "85 poäng men materialet saknas i produktunderlaget.", result: "Produkten blir inte rekommenderad utan kontroll, trots att poängen överstiger 75." } }),
      rule("mojlig", "35 poäng är gränsen för möjlig kandidat", "Villkoren för rekommenderad är inte uppfyllda.", "Minst 35 poäng ger möjlig kandidat. Under 35 ger osannolik. Konstaterad teknisk konflikt omfattas alltid av konfliktregeln."),
      rule("konflikt", "Teknisk konflikt ger högst 34 poäng", "En igenkänd teknisk konflikt finns, exempelvis fel DN, K, material, SDR, mätområde eller system.", "Sätt högst 34 poäng, markera osannolik och ta bort exakt match. Katalog- eller NRF-bonus får inte upphäva konflikten.", { kind: "requirement", notes: ["Saknad uppgift är kontrollbehov, inte automatiskt bevis för fel produkt.", "Konflikter identifieras för särskilda varningstyper. Inte varje varning betyder konstaterad inkompatibilitet."] }),
      rule("exakt-match", "Exakt match kräver komplett underlag", "Alla nödvändiga tekniska värden styrks, inga varningar finns och varken tillbehör eller artikelvariant återstår att välja.", "Tillåt exakt match vid giltig exakt katalogbedömning eller fullständig slutbedömning med 100 poäng. En ren PDF-hänvisning räcker inte."),
      rule("sortering", "Färre varningar går före högre poäng", "Flera kandidater ska visas i ordning.", "Sortera först på bedömningsnivå, därefter färre varningar, högre poäng, sortimentsprioritet, eventuella historiska stödfält och sist produktnamn.", { notes: ["Konstaterade konflikter placeras efter ofullständiga men möjliga produkter.", "Historiska likhetsfält i sorteringen innebär inte att fri självlärande matchning är aktiv."] }),
      rule("mldl-bonus", "Strukturerad kataloginformation ger bonus", "En kandidat har matchande NRF, modell eller strukturerade egenskaper i MLDL.", "Lägg på katalogbonusen och tillämpa sedan konfliktregeln igen. Behåll alla kvarstående varningar.", { table: table(["Signal", "Effekt"], [["Exakt NRF i kravunderlaget", "Sätt 100 före konfliktbegränsning"], ["Modell", "+25"], ["Produkttyp", "+15"], ["Minst 2 särskiljande ord", "+2 per ord, högst +12"], ["MLDL och offentlig katalog, inga varningar", "+8"]]) }),
      rule("eidsvoll", "LC Eidsvoll får företräde vid lika bedömning", "Kandidater är likvärdiga efter bedömningsnivå, varningar och poäng.", "Prioritera artikel i LC Eidsvolls sortiment. Ingen egen poängbonus och ingen teknisk konflikt försvinner.", { kind: "assumption" }),
      rule("grundpoang", "Rätt produktfamilj ger grundpoäng", "Kandidatens produktfamilj motsvarar kravet.", "Lägg till familjens grundpoäng, därefter tekniska jämförelser. En familjeträff ensam verifierar inte hela posten.", { table: table(["Familj", "Grundpoäng"], [["De flesta ventiler, rördelar, mätare, pumpar, skåp och sanitetsprodukter", "+65"], ["Rak rörlängd / sprinklerslang", "+65"], ["Kulventil", "+55"], ["Tryckvakt", "+75"], ["Sprinklerhuvud", "+25"], ["Skyddskorg", "+80"], ["Flänsböj", "+45"], ["Torr alarmventil", "+65 familj, +65 torrt"], ["Våt alarmventil", "+30 komplett, +25 våt, +15 alarm, +10 serie 751"]]) }),
      rule("fel-familj", "Tillbehör får inte ersätta huvudprodukten", "Träffen är en rördel, skylt, reservdel eller ett tillbehör till det som ska väljas.", "Filtrera bort fel familj eller ge avdrag och kontroll/konflikt enligt familjens regel.", { table: table(["Fel träff", "Avdrag"], [["Tillbehör till kulventil", "−80"], ["Tillbehör till huvud/slang", "−70"], ["Reservdel till avstängningsventil", "−65"], ["Vissa rör/rördelsförväxlingar", "−55"], ["Manometer i stället för tryckvakt eller tvärtom", "−60"], ["Waterguard-komponent mot kulventil", "−45"]]) })
    ]
  },
  {
    id: "teknik", title: "Tekniska grundkrav", appliesTo: "Produkter med motsvarande krav i PDF-posten", kind: "requirement",
    description: "Dimension, tryck, material och anslutning jämförs med den valda artikeln.",
    sources: ["ahlsell-candidate-ranking.ts", "ahlsell-engineering-checks.ts", "pipe-technical-terms.ts"],
    rules: [
      rule("dimension", "Dimensionen ska stämma", "PDF-posten anger DN eller en relevant ytterdiameter.", "Rätt dimension ger +25. Fel dimension ger −45 och teknisk konflikt. Saknad dimension ger kontrollbehov.", { notes: ["En annan uttrycklig DN får inte döljas av att rätt ytterdiameter nämns någon annanstans på artikeln.", "Rör kan bedömas på egen ytterdiameter när DN saknas. Sprinkler K80/DN25 har ett särskilt korrigeringsundantag.", "Dimensionskrav behövs för rör, ventiler, kopplingar, böjar, T-rör, reduktioner, ändlock, avstick och flänsadaptrar."], example: { input: "PDF: DN50. Produkt: DN65.", result: "Fel dimension. Kandidaten får högst 34 poäng efter konfliktregeln och kan inte bli exakt match." } }),
      rule("pn", "Tryckklassen ska styrkas", "PDF-posten anger PN.", "Styrkt PN ger +10. Annan PN ger −20 och konflikt; saknad uppgift ger varning. Högre PN accepteras inte generellt som likvärdigt.", { notes: ["Uttryckligt minimum trykklasse PN i generella rörkrav tillåter högre klass.", "Motsvarande barvärde i produkttexten kan också ge stöd i PN-jämförelsen. Arbetstryck kontrolleras separat."] }),
      rule("arbetstryck", "Tillåtet arbetstryck måste täcka kravet", "PDF-posten anger arbetstryck och produkten har dokumenterad tryckkapacitet.", "Kontrollera att tillåtet arbetstryck är minst kravet. För lågt tryck är konflikt, okänd kapacitet kräver kontroll. Provtryck räknas inte som arbetstryck.", { notes: ["kPa × 0,01, MPa × 10 och psi × 0,0689476 normaliseras till bar.", "Motstridiga tryckuppgifter hanteras försiktigt; ett högt värde får inte ensamt dölja ett lägre dokumenterat värde."] }),
      rule("material", "Materialet ska stämma", "PDF-posten har ett igenkänt materialkrav.", "Samma material ger +10. Annat material ger −55 och konflikt. Saknat material kräver kontroll.", { notes: ["Materialgrupper: stål, rostfritt, PP-R, PE, PVC, koppar, flerskiktsrör, mässing och duktilt gjutjärn.", "Rörets kropp bedöms, inte materialet hos ett annat rör som artikeln beskrivs som tillbehör till."] }),
      rule("skarv", "Anslutnings- och skarvtyp ska stämma", "Kravet anger skarv eller anslutning.", "Tillåten typ ger +10. Annan igenkänd typ ger −55 och konflikt. Saknad uppgift kräver kontroll.", { notes: ["Gängat, rillat, svetsat, fusion och flänsat har särskild normalisering.", "Uttryckligt eller/or kan tillåta flera alternativ. Generella rörregler kan tillåta rillade rör."] }),
      rule("rostfri-kvalitet", "Rostfri kvalitet jämförs separat", "PDF anger igenkänd kvalitet som 304, 304L, 316, 316L eller 904L.", "Samma kvalitet ger stöd utan extra poäng. Fel kvalitet ger −55 och konflikt. Saknad kvalitet eller dokumenterad likvärdighet kräver kontroll."),
      rule("korrosion", "Korrosionsklass måste framgå", "En C1–C5-korrosionskategori har identifierats i kravprofilen.", "Kräv stöd för samma klass i produkten. Om klassen inte styrks visas kontrollbehov.", { notes: ["Kontrollen förutsätter att textmönstret identifierats; den tolkar inte automatiskt alla möjliga formuleringar om korrosion."] }),
      rule("toleranser", "Använd fasta numeriska toleranser", "Två numeriska egenskaper jämförs.", "Vanliga dimension-/temperaturjämförelser kräver mindre än 0,05 i skillnad. Böjvinkel använder 0,1°. K-faktor och SDR har egna regler."),
      rule("ip", "IP-klass måste dokumenteras", "PDF-posten anger en IP-klass.", "Om efterfrågad klass saknar stöd i produktunderlaget krävs manuell kontroll.", { kind: "review", notes: ["Dagens kontroll söker efter samma två IP-siffror i produkttexten. Den räknar inte ut om en annan kapslingsklass kan uppfylla eller överträffa kravet."] })
    ]
  },
  {
    id: "sprinkler", title: "Sprinklerhuvuden", appliesTo: "Sprinklerhuvuden", kind: "requirement",
    description: "K, temperatur, riktning, montage och de särskilda sprinklerundantagen.",
    sources: ["ahlsell-candidate-ranking.ts", "sprinkler-technical-rules.ts", "ahlsell-public-match.ts"],
    rules: [
      rule("sprinkler-underlag", "Åtta huvuduppgifter behövs", "Ett sprinklerhuvud ska bedömas som verifierat.", "Kravprofilen behöver gängdimension, K, temperatur, respons, riktning, anläggningstyp, sprinklerutförande och täckningsklass. Saknade uppgifter ger kontrollbehov."),
      rule("k-faktor", "K-faktorn ska stämma", "PDF och produkt har K-faktor.", "Rätt K ger +25. Fel K ger −55 och konflikt. Saknat värde kräver kontroll.", { notes: ["Mindre än 0,11 i skillnad accepteras. Om båda värdena är minst 50 accepteras upp till 1,1, exempelvis K115/K115,5.", "K-80 tolkas som positivt K80. Orimliga värden rättas inte genom att hitta på en decimal."], example: { input: "PDF: K80. Produkt: K115.", result: "Teknisk konflikt. Bonus för fabrikat eller artikelnummer kan inte upphäva den." } }),
      rule("temperatur", "Utlösningstemperaturen ska stämma", "PDF-posten anger utlösningstemperatur.", "Rätt temperatur ger +15. Fel temperatur ger −35 och konflikt. Saknad temperatur ger varning."),
      rule("respons", "QR och SR får inte förväxlas", "PDF-posten anger quick- eller standardrespons.", "Rätt respons ger +12. Fel ger −35 och konflikt. Blandade QR/SR-krav i samma post kräver kontroll."),
      rule("riktning", "Upp, ned och vägg är olika utföranden", "Monteringsriktning anges.", "Rätt riktning ger +15. Fel ger −45 och konflikt. Uttrycklig upp/ned-produkt kan stödja båda, men inte väggmontage.", { notes: ["Korta Opp/Ned-ord kontrolleras försiktigare i produktnamnet. Opp til ska inte ge uppåtriktning.", "Blandade riktningar i PDF ger varning. Infällt/dolt takmontage kan stödja nedåtriktning om det inte finns en motsägelse."] }),
      rule("montage", "Synligt, infällt och dolt skiljs åt", "PDF anger montage eller uttryckligt synligt utförande.", "Kräv dokumenterat stöd för rätt montage. Rosettvillkor ensamt bevisar inte att montaget ska vara infällt.", { table: table(["Kontroll", "Poäng"], [["Synligt utförande stämmer", "+15"], ["Infällt/dolt montage stämmer", "+30"], ["Dold mot synligt krav", "−70"], ["Ytmonterat mot infällt/dolt", "−65"], ["Annat fel montage", "−60"], ["Montage inte styrkt", "−20 och varning"]]), notes: ["Inlagda modellregler omfattar V2762 för infällt och V2726 för konventionellt montage."] }),
      rule("huvudtyp", "Standard, torrt och öppet huvud skiljs åt", "PDF anger sprinklerhuvudets konstruktion.", "Rätt konstruktion ger +15. Fel eller otillräckligt dokumenterat utförande ger −60 och kontroll/konflikt beroende på vad som faktiskt är känt."),
      rule("vat-torr", "Torr anläggning är inte samma som torrsprinkler", "Anläggningstyp och produktens systembegränsning ska jämföras.", "Uttryckligt kompatibelt system ger +8, uttryckligt fel system −60. Ett normalt huvud utesluts inte enbart för att anläggningen är torr."),
      rule("tackning", "Täckningsklassen ska stämma", "PDF anger täckningsklass.", "Rätt klass ger +10, fel klass −35 och konflikt. Generellt extended kan täckas av extended/LH/OH; andra klasser jämförs specifikt.", { notes: ["Klasser omfattar standard, extended, LH, OH, bostad, lager/ESFR, riktad öppen dysa, fönster, institution och korridor."] }),
      rule("finish", "Angiven färg och finish ska stämma", "PDF anger vit, svart, krom eller mässing.", "Rätt finish ger +5. Fel ger −15 och konflikt. Saknad efterfrågad uppgift ger kontrollbehov."),
      rule("hydraulik", "Specialtäckning kräver hydraulisk kontroll", "Specialtäckning, minimitryck eller hydraulisk beräkning efterfrågas.", "Markera kontrollbehov. Scipx utför inte en fullständig hydraulisk dimensionering.", { kind: "review" }),
      rule("k-dn-undantag", "Kontrollera särskilda K/DN-kombinationer", "K ≥ 115 kombineras med DN15, eller konventionell K80 anges med DN25.", "K ≥ 115/DN15 ger varning och −25. K80/DN25 kan visa DN15 som korrigeringsförslag med −20 och manuell bekräftelse.", { kind: "assumption", notes: ["Torrsprinkler med annan DN än 25 får särskild varning i sökguiden utifrån inlagda katalogfamiljer.", "PDF-värdet ändras inte automatiskt av dessa regler."] })
    ]
  },
  {
    id: "ror", title: "Rör & rördelar", appliesTo: "Rör, kopplingar, böjar och övriga rördelar", kind: "requirement",
    description: "Dimensioner, SDR, material och leveranser som innehåller flera delar.",
    sources: ["pipe-matching-evidence.ts", "pipe-product-family.ts", "ahlsell-engineering-checks.ts", "ahlsell-candidate-ranking.ts"],
    rules: [
      rule("ror-kropp", "Använd rörets egen kropp och dimension", "Artikeltexten nämner flera material eller anslutningar.", "Prioritera rörets egna dimensionsfält och kroppsmaterial. En ändfläns DN blir inte rörets ytterdiameter och för PE-rör betyder inte tillverkad i PE.", { notes: ["Ø och tal med mm läses som ytterdiameter; DN läses som nominell dimension. Ett ensamt tal i ett dimensionsfält tolkas som DN om fältet inte uttryckligen heter ytterdiameter.", "Om eget dimensionsfält saknas stoppas tolkningen före uttryck som med flens, avsluttes eller inkludert, så att en annan del inte blir rörets egen dimension."] }),
      rule("dn-od", "Översätt DN med den fasta rörtabellen", "En tillämplig DN behöver jämföras med ytterdiameter.", "Använd tabellen. Skapa inte alternativa plast-/kopparsökdimensioner från stålrörstabellen.", { table: table(["DN", "Ytterdiameter mm"], [["15 / 20 / 25", "21,3 / 26,9 / 33,7"], ["32 / 40 / 50", "42,4 / 48,3 / 60,3"], ["65 / 80 / 100", "76,1 / 88,9 / 114,3"], ["125 / 150 / 200", "139,7 / 168,3 / 219,1"]]) }),
      rule("sdr", "SDR ska stämma", "PDF anger SDR.", "Skillnad över 0,01 är konflikt. Saknad SDR kräver kontroll. Ett annat dokumenterat SDR-värde får inte döljas av att ett rätt värde också nämns."),
      rule("pma", "PMA måste styrkas separat", "PDF anger tillåtet driftstryck/PMA.", "Dokumenterad kapacitet måste täcka kravet. En PN-uppgift ensam är inte alltid bevis för PMA."),
      rule("flera-anslutningar", "Kontrollera alla relevanta anslutningar", "T-rör, reduktion eller avstick har flera dimensioner.", "Kontrollera de olika anslutningarnas DN. Rätt huvud-DN räcker inte om avsticket är fel. Saknade dimensioner ger kontrollbehov."),
      rule("andelock", "Ändlockets DN och skarv ska höra ihop", "Ett ändlock eller en plugg har flera angivna anslutningar.", "Håll DN och anslutningstyp på samma primära anslutning. Flera omärkta anslutningar ger osäker bedömning."),
      rule("bojvinkel", "Böjvinkel och mängdenhet kontrolleras", "Posten är en böj.", "Jämför angiven vinkel med tolerans 0,1°. Saknad vinkel eller mängdsättning i meter ger manuell kontroll. Fel vinkel är konflikt.", { notes: ["För flänsböj finns ett särskilt avdrag på −35 för duktilt gjutjärn när stål krävs, utöver tillämpliga gemensamma materialkontroller."] }),
      rule("ror-ytbehandling", "Kontrollera galvanisering, pressförbud och målning", "PDF innehåller igenkända generella rörkrav.", "Flagga saknad galvanisering. Pressprodukt mot uttryckligt pressförbud ger avvikelse. RAL9010, primer och kapade ändar kan kräva kontroll av målningssystem.", { kind: "review" }),
      rule("ror-komplett", "Rör inklusive delar är en hel leverans", "PDF kräver rör inklusive böjar, kopplingar, T-rör, ändlock eller upphängning.", "Skapa komponentbehov och begär kontroll av hela leveransen. Rörartikeln ensam verifierar inte hela posten och antal rördelar räknas inte fram ur rörmeter.", { kind: "review" })
    ]
  },
  {
    id: "ventiler", title: "Ventiler & instrument", appliesTo: "Ventiler, manometrar, tryckvakter och flödesmätare", kind: "requirement",
    description: "Funktion, övervakning, larm och rätt mätområde.",
    sources: ["ahlsell-candidate-ranking.ts", "ahlsell-engineering-checks.ts", "ahlsell-mldl-catalog.ts"],
    rules: [
      rule("ventil-overvakning", "Övervakning ska motsvara kravet", "PDF kräver övervakad ventil i öppet läge.", "Övervakad öppen ger +30. Övervakad stängd ger −70 och konflikt. Ej styrkt övervakning ger −35 och varning.", { notes: ["Om kravet uttryckligen är utan övervakning kan en övervakad produkt vara fel utförande.", "Kulventil med lägesgivare kräver dokumenterat stöd för givaren och funktionen."] }),
      rule("ventil-manover", "Handratt och mjuk stängning kontrolleras", "PDF kräver handratt/växel eller mjuk kontrollerad stängning.", "Handratt ger +15; spak i stället −35. För mjuk stängning ger handratt/växel +10, spak −25. Okänd manövrering kräver kontroll."),
      rule("serie-705", "Serie 705 har inlagda tekniska uppgifter", "En identifierad FireLock 705-artikel bedöms.", "Komplettera med övervakad öppen, växlad handratt, kontrollerad stängning, duktilt hus, OGS och 21 bar.", { kind: "assumption", notes: ["Detta är en särskild katalogregel och gäller inte automatiskt andra ventiler från samma fabrikat."] }),
      rule("backventil", "Fjäder och vätskekategori kontrolleras", "PDF kräver fjäderbelastad backventil eller användning för vätskekategori 4.", "Fjäder styrkt ger +10; uttryckligen utan fjäder ger −60. Vätskekategori 4 kräver dokumentation för användningen."),
      rule("alarmventil", "Alarmcentral skiljs från ventil och reservdel", "En våt eller torr alarmventil/central efterfrågas.", "Kontrollera systemtyp och komplett utförande. En skylt, reservdel eller vanlig avstängningsventil räcker inte.", { table: table(["Avvikelse mot våt alarmventil", "Avdrag"], [["Torrt utförande", "−60"], ["Vanlig avstängningsventil", "−40"], ["Bostadsutförande utan sådant krav", "−25"], ["Skylt / reservdel", "−60 / −40"]]), notes: ["Alarmgivare, extralarm, retardkammare och komplett trim kan behöva separat leveranskontroll."] }),
      rule("tryckinstrument", "Tryckvakt och manometer har olika funktion", "PDF anger tryckvakt eller manometer.", "Skilj mätning från brytande kontaktfunktion. Manometer kan få +10 för sprinkleranknytning. Tryckvaktens område, kontakter, maxtryck och kompatibilitet kräver kontroll.", { kind: "review" }),
      rule("flodesomrade", "Flödesmätaren ska täcka hela intervallet", "PDF anger ett mätområde.", "Produktens nedre gräns ska vara högst kravets nedre och den övre minst kravets övre. Fel intervall är konflikt, saknat intervall är kontrollbehov.", { notes: ["Sprinkleranvändning, anslutningar och komplett leverans kontrolleras dessutom manuellt."], example: { input: "Krav 100–1 000 l/min. Produkt 200–1 200 l/min.", result: "Produkten täcker inte den nedre delen. Mätområdet är fel trots att maxflödet är tillräckligt." } })
    ]
  },
  {
    id: "komplett", title: "Kompletta installationer", appliesTo: "Sammansatta leveranser och specialprodukter", kind: "review",
    description: "Rätt huvudprodukt innebär inte automatiskt att hela leveransen är verifierad.",
    sources: ["ahlsell-engineering-checks.ts", "product-assembly-plan.ts", "ahlsell-candidate-ranking.ts"],
    rules: [
      rule("fordelarskap", "Kontrollera komplett fördelarskåp", "PDF efterfrågar fördelarskåp.", "Kontrollera skåp, fördelare, utlopp, anslutningar, avrinning och leveransomfattning. Gemensam jämförelse av skåpets material/PN/DN används inte som om det vore ett rör."),
      rule("sanitet", "Kontrollera komplett WC och dusch", "PDF efterfrågar toalett eller dusch.", "Kontrollera ingående delar, utförande, belastning, infästning, höjdjustering, stödhandtag och andra efterfrågade tillval."),
      rule("pump", "Kontrollera pumpens driftpunkt och utförande", "PDF anger pump och tekniska driftkrav.", "Kontrollera flöde, uppfordringshöjd, spänning och tillbehör när dessa efterfrågas.", { notes: ["Länspump för relevant avloppsvatten/nedsänkt utförande kan få +15. Grundvattenpump mot avloppsvatten ger −30 och varning."] }),
      rule("reservskap", "Kontrollera innehållet i reservsprinklerskåpet", "Posten kräver skåp för reservsprinkler.", "Kontrollera antal och utförande på huvuden, nycklar och övrigt innehåll. Skåpträffen ensam verifierar inte leveransen."),
      rule("installationsdelar", "Kontrollera extra leveransdelar", "PDF kräver komplett test/dränering, spolanslutning, givarficka, filter, flänsadapter, alarmset eller mätarset.", "Kontrollera extra komponenter som nämns i posten. Rätt huvudfamilj är bara en del av bedömningen."),
      rule("specialtillverkning", "Specialtillverkning kräver offert eller eget val", "Posten verkar avse exempelvis specialtillverkat dränerings- eller uppsamlingskar.", "Begär manuell kontroll/offert. En generell artikelträff verifierar inte den specialtillverkade produkten."),
      rule("aktuator", "Kontrollera nyckelbrytare och aktuator", "Huvudprodukten är nyckelbrytare eller ventilaktuator.", "Rätt familj ger +65 men funktion och kompatibilitet med ansluten utrustning kräver fortsatt kontroll.")
    ]
  },
  {
    id: "kallor", title: "Artikeldata & verifiering", appliesTo: "MLDL, Ahlsell och verifierade tillverkaruppgifter", kind: "requirement",
    description: "Samma artikelnummer, tillförlitliga fält och kvarstående motsägelser.",
    sources: ["ahlsell-technical-evidence.ts", "ahlsell-product-subtitle.ts", "ahlsell-candidate-merge.ts", "victaulic-sprinkler-catalog.ts", "victaulic-working-pressure.ts", "ahlsell-public-match.ts"],
    rules: [
      rule("artikelidentitet", "Tekniska data måste höra till rätt artikel", "En produktsida eller variantlista hämtas.", "Kontrollera synlig artikelidentitet och märkta specifikationer. Rekommenderade produkter, en annan variant eller värden från sökfrasen är inte bevis för artikelns egenskaper.", { notes: ["Produktsidor hämtas endast från tillåtna Ahlsell-adresser, med högst två omdirigeringar, 3 MB och fyra sekunders timeout.", "Högst 60 märkta specifikationsfält läses från en produktsida."] }),
      rule("sparad-evidens", "Behåll källa och hämtningstid", "Tekniska egenskaper hämtas från Ahlsell.", "Spara råvärde, URL, källtyp och tid. Underlaget omfattar DN, Ø, gänga, material, kvalitet, anslutning, PN, arbetstryck, K, temperatur, respons, riktning och finish."),
      rule("evidens-konflikt", "Motstridiga uppgifter kräver kontroll", "Underlaget innehåller olika värden, fel NRF eller för gamla uppgifter.", "Behåll osäkerheten. Underlag äldre än 12 timmar kan behöva hämtas om. Gissa inte saknade egenskaper utifrån familjen.", { kind: "review" }),
      rule("sammanfoga", "Slå ihop samma NRF utan att dölja varningar", "MLDL och offentlig katalog beskriver samma normaliserade artikelnummer.", "Komplettera text och specifikationer. Behåll olösta konflikter, tillbehörskrav och variantval. Om ny säker data fyller en lucka kan motsvarande saknas-varning omprövas."),
      rule("direkt-katalog", "Direkta sprinklerförslag har strikta villkor", "Sökguiden kan använda en inlagd standardartikel.", "För norskt underlag används Victaulic-katalogen. Annat underlag kan använda standardlistan när K, DN, temperatur, riktning, respons och finish stämmer utan motsägelser eller specialutförande.", { notes: ["Direkta kandidater begränsas sedan till MLDL-artiklar; ren PDF-hänvisning räcker inte.", "Offentlig sökning kan komplettera med andra artiklar."] }),
      rule("victaulic-urval", "Victaulic-katalogen har ett eget första urval", "K och DN finns och en Victaulic-kandidat ska hämtas.", "Filtrera på modell, K, DN, konstruktion, montage, täckning och system. Bedöm sedan kandidaten med den gemensamma motorn.", { kind: "ranking", table: table(["Första katalogbedömning", "Poäng"], [["Grund", "65"], ["Temperatur", "+10 / −10"], ["Respons, riktning, montage", "+8 / −8 vardera"], ["Finish", "+4 / −4"], ["Varje varning", "ytterligare −8"]]), notes: ["Katalogen hanterar angivna K-representationer i katalog-, SI- och imperialdata."] }),
      rule("victaulic-exakt", "Verifierat SIN krävs för exakt katalogträff", "En Victaulic-artikel ska få exaktflagga i katalogsteget.", "Kräv verifierad artikel/SIN, kompletta variantuppgifter och inga kontrollflaggor. Snabbvägen gäller enkelt dokumenterat standardutförande utan olösta montage- eller tillbehörskrav.", { notes: ["Om flera exakta alternativ återstår krävs produktval och exaktflaggan tas bort."] }),
      rule("victaulic-tryck", "Tillverkartryck kopplas till exakt modell", "En artikel kompletteras med Victaulics arbetstryck.", "Använd den identifierade artikeln/modellen och lagrad tillverkarpublikation. Fabrikatets namn ensamt räcker inte.")
    ]
  },
  {
    id: "tillbehor", title: "Tillbehör", appliesTo: "Vald huvudprodukt och postens leveranskrav", kind: "requirement",
    description: "När tillbehör visas, hur de väljs och vilka mängder som följer med.",
    sources: ["product-assembly-plan.ts", "sprinkler-assembly-plan.ts", "assembly-component-lookup.ts", "assembly-component-matching.ts", "ahlsell-accessory-suggestions.ts", "product-card-accessories.ts"],
    rules: [
      rule("tillbehor-huvud", "Alla huvudproduktval kan leda till tillbehör", "Användaren väljer ett förslag eller lägger till en produkt från Ahlsell.", "Utgå från PDF-kravet och vald huvudartikel. Slå upp huvudartikeln i MLDL eller på Ahlsell och skapa relevant tillbehörsplan."),
      rule("tillbehor-status", "Skilj obligatoriskt från valfritt", "En möjlig komponent nämns i posten.", "Klassificera som obligatorisk, valfri, inte krävd, inte tillämplig eller behöver kontroll. Nei/IR/NA kan innebära inte krävd, valgfritt innebär valfri."),
      rule("rosett-villkor", "Rosett vid infällning är ett villkor", "Texten anger dekkskive/pyntering ved innfelling.", "Infällt/dolt montage gör delen relevant. Utan sådant montage kan den vara ej tillämplig. Oklart montage ger kontrollbehov.", { example: { input: "Dobbel rosett ved innfelling, men montage saknas.", result: "Begär kontroll av montagevillkoret. Anta inte automatiskt att rosett måste köpas." } }),
      rule("separat-post", "Undvik dubbelköp från grannpost", "En ingående del redan har en separat mängdsatt post.", "Lägg inte automatiskt till samma del en gång till som tillbehör till huvudprodukten."),
      rule("slang-faste", "Fästmateriel följer slangkravet", "Slangposten uttryckligen omfattar fästmateriel.", "Skapa behov av monteringsdel/fäste efter valet av huvudslang. Det gäller även manuellt tillagd huvudprodukt."),
      rule("komponent-urval", "Sök komponenter inom rätt familj", "Tillbehör ska föreslås automatiskt.", "Använd komponenttyp och huvudartikel. Granska högst 24 kandidater per fras, två sidor, fyra variantfamiljer och sex detaljsidor."),
      rule("komponent-teknik", "Kontrollera anslutning och kompatibilitet", "Rördelar eller sprinklerdelar föreslås.", "Filtrera kända fel i familj, DN, skarv, tryck och modellkompatibilitet. IGS, OGS och StrengThin är inte automatiskt samma system.", { notes: ["Rördelens material behöver inte vara samma som rörkroppens. Systemkompatibilitet behöver ibland granskas separat.", "Skåpdelar filtreras på familj; full leveranskompatibilitet återstår att kontrollera.", "Modellord i en sökfras är inte i sig ett kompatibilitetsbevis."] }),
      rule("tillbehor-poang", "Lokala tillbehör har eget urval", "MLDL har tillbehör för huvudprodukten.", "Prioritera relevant modellfamilj och dimension, men behåll nödvändiga kompatibilitetskontroller.", { kind: "ranking", table: table(["Typ", "Urval"], [["Sprinklerdel", "Familj +50, DN +20, finish +15, typ +20; max 3 per typ"], ["Slangfäste", "Uttrycklig familj +100, generiskt +30; max 3"], ["Torrventil 768/769", "Relevant trim/accelerator; max 3"], ["Våtventil 751", "Trim med relevant DN; max 2, beakta ingående FG-trim"]]) }),
      rule("byte-huvudprodukt", "Nytt NRF rensar tillbehörsvalen", "Huvudproduktens NRF ändras.", "Rensa tillbehören så att gamla komponenter inte följer med en annan huvudprodukt. Samma NRF behåller valen."),
      rule("tillbehor-mangd", "Tillbehörsmängden måste vara giltig", "Tillbehör sparas med huvudprodukten.", "Tillåt högst 20 utan dubbletter och giltigt antal 0,001–100 000. Mängd per huvudprodukt kan multipliceras med postens antal; okänd mängd ska inte hittas på.", { notes: ["Rördelsmängd bestäms från ritning/leverans, inte genom att använda antal meter som antal tillbehör."] })
    ]
  },
  {
    id: "historik", title: "Tidigare produktval", appliesTo: "Produktminne inom samma kundorganisation", kind: "search",
    description: "Vad exakt tidigare val betyder och när det får återanvändas.",
    sources: ["distributor-product-memory.ts", "distributor-product-memory-match.ts"],
    rules: [
      rule("historik-org", "Historik hålls inom organisationen", "Tidigare val ska visas för ett krav.", "Använd samma organisation, distributören Ahlsell och identiskt kravfingeravtryck. Raderade minnen och val med granskningsreservationer används inte som vanliga exakta historiska val."),
      rule("fingeravtryck", "Identiska krav avgör historikträffen", "Två krav jämförs för återanvändning.", "Fingeravtrycket byggs av kategori, kravnyckel, produkttext, operation, system och strukturerade egenskaper.", { notes: ["Postnummer, PDF-sida och totalmängd är inte egna delar, men kan påverka om de är inbäddade i text eller egenskaper."] }),
      rule("historik-urval", "Historiska artiklar behöver finnas i MLDL", "Produktkortet visar tidigare val.", "Kräv MLDL-artikel och, för rör, en faktisk rörprodukt. Sortera efter användningsantal och senaste användning."),
      rule("historik-betydelse", "Exakt historik är inte en ny teknisk verifiering", "Ett identiskt krav har ett tidigare godkänt val.", "Visa historikens stöd men skilj det från en ny teknisk bedömning. Denna väg kör inte om hela den aktuella kandidatrankningen. Produkten måste godkännas igen i projektet.", { kind: "review" }),
      rule("historik-larande", "Likhetskod är inte aktiv självlärning", "Koden innehåller hjälpfunktioner för liknande historiska krav eller registrerar visningar och val.", "Det innebär inte att fri likhetsmatchning eller automatisk modellträning är inkopplad i den aktuella sökvägen.", { kind: "gap" })
    ]
  },
  {
    id: "manuellt", title: "Manuellt val & visning", appliesTo: "Produktkort och eget produktval", kind: "review",
    description: "Manuell sökning, listans status och användarens godkännande.",
    sources: ["ahlsell-product-lookup.ts", "product-selection-review.ts", "ahlsell-match-groups.ts"],
    rules: [
      rule("manuell-sok", "Sök manuellt med NRF, namn eller länk", "Användaren söker eller lägger till produkt.", "Ta emot NRF, produktnamn eller Ahlsell-URL. Slå först upp exakt NRF; reservsökning ger upp till tolv produkter, fyra variantfamiljer och sex detaljsidor.", { notes: ["Vanlig söktext begränsas till 2–180 tecken. En URL får vara högst 2 000 tecken."] }),
      rule("ersattningsartikel", "Byt inte tyst till ett nytt artikelnummer", "Exakt NRF-sökning leder till en ersättningsartikel med annat NRF.", "Acceptera inte ersättningen som samma artikel. Visa att det efterfrågade numret inte kunde bekräftas."),
      rule("manuellt-teknik", "Manuellt hittad produkt bedöms också", "Användaren väljer en produkt från Ahlsell.", "Kör teknisk bedömning och behåll varningar. Manuell sökning kan visa annan familj med varning; den automatiska vägen filtrerar bort fler sådana träffar."),
      rule("visning-kandidater", "Visa möjliga kandidater för kontroll", "Kandidater ska listas i produktkortet.", "Dölj konstaterade felträffar från vanliga förslag. Visa möjliga produkter med ofullständigt underlag. Sammansatt leverans eller PDF-varningar kan göra att kortet visar kontroll trots stark enskild kandidat."),
      rule("godkannande", "Användarens godkännande är separat", "Användaren godkänner en vald huvudprodukt.", "Spara det uttryckliga beslutet separat från teknisk match. Ett manuellt avvikande val kan sparas med granskningsuppgifter; tekniska varningar är inte alla absoluta sparspärrar."),
      rule("sparsparrar", "Ofärdiga formulär hindrar sparandet", "Mängder eller tillbehör är ogiltiga, eller kommentar/bilaga har ett osparat utkast.", "Hantera formulärfelet eller utkastet innan godkännande och sparande."),
      rule("triangel", "Triangeln betyder att produkt inte valts", "Posten saknar vald produkt.", "Visa triangel i översikten. Symbolen är inte i sig en teknisk kvalitetsbedömning.")
    ]
  },
  {
    id: "luckor", title: "Kontroller som saknas", appliesTo: "Krav som inte täcks fullständigt av dagens motor", kind: "gap",
    description: "Tydliga begränsningar i dagens regler. Dessa är inte aktiva verifieringsregler.",
    sources: ["ahlsell-candidate-ranking.ts", "ahlsell-engineering-checks.ts", "ahlsell-public-match.ts", "sprinkler-assembly-plan.ts"],
    rules: [
      rule("fri-kravtext", "Alla fria krav maskinkontrolleras inte", "PDF-posten innehåller fri text under exempelvis Andra krav a), b), c).", "Texten kan vara sparad och synlig utan att varje mening har en automatisk jämförelseregel. Endast igenkända fält och textmönster kontrolleras."),
      rule("braided-langd", "Braided och ekvivalent slanglängd saknar slutkontroll", "Slangposten kräver braided-utförande och högst 15 m ekvivalent längd.", "Slang och fästmateriel känns igen, men det finns ingen särskild slutjämförelse som verifierar dessa två egenskaper. De behöver kontrolleras manuellt.", { example: { input: "Flexislange braided, max ekvivalent längd 15 m.", result: "En slangträff innebär inte att braided-utförande och hydraulisk ekvivalentlängd har blivit verifierade." } }),
      rule("pex-material", "PEX har inte en egen slutlig materialkategori", "Sökningen identifierar PEX.", "PEX kan styra sökfrasen men saknar egen materialkategori i den gemensamma slutliga materialjämförelsen. Stödet är därför ojämnt."),
      rule("standarder", "Alla standarder och godkännanden verifieras inte", "PDF hänvisar till NS/EN, FM/UL eller fullständig hydraulisk dimensionering.", "Ingen generell fullständig verifiering finns för alla sådana krav. Särskilda kontroller kan finnas, men ersätter inte en fullständig verifiering."),
      rule("sortiment-omfattning", "Ingen träff betyder inte att produkten saknas", "Sökningen undersöker endast ett begränsat urval eller misslyckas delvis.", "En lämplig produkt eller variant kan finnas utanför urvalet. Manuell sökning eller kontroll kan behövas."),
      rule("poang-bevis", "Två källor verifierar inte alla krav", "Samma artikel finns i både MLDL och offentlig katalog, eller har hög poäng.", "Det ger katalogstöd men inte bevis för att varje PDF-krav är uppfyllt. Historik, poäng, teknisk match och användargodkännande måste skiljas åt.")
    ]
  }
];

export const MATCHING_RULES = MATCHING_RULE_GROUPS.flatMap(group => group.rules.map(item => ({
  ...item, kind: item.kind ?? group.kind, groupId: group.id, groupTitle: group.title,
  appliesTo: group.appliesTo, sources: group.sources
})));
export type CatalogRule = (typeof MATCHING_RULES)[number];

export function normalizeRuleSearch(value: string) {
  return value.toLocaleLowerCase("sv").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ø/g, "o").replace(/æ/g, "ae");
}
export function filterMatchingRules(query: string, kind: string = "all") {
  const words = normalizeRuleSearch(query.trim()).split(/\s+/).filter(Boolean);
  return MATCHING_RULES.filter(item => {
    if (kind !== "all" && item.kind !== kind) return false;
    const haystack = normalizeRuleSearch([item.title, item.id, item.groupTitle, item.appliesTo, item.when, item.result,
      ...(item.notes ?? []), ...(item.table?.rows.flat() ?? []), item.example?.input ?? "", item.example?.result ?? ""].join(" "));
    return words.every(word => haystack.includes(word));
  });
}

export function ruleSourceUrl(file: string) {
  return `https://github.com/MarcLars31/FlowX-Platform/blob/${RULE_CATALOG_VERSION}/apps/web/src/lib/${file}`;
}
